/**
 * GENERATED by docs/flight-guides/_tools/write-app-content.mjs.
 * Do not edit by hand: the reviewed source is docs/flight-guides/, and
 * this file is rewritten from it. Change a value there, run the tool.
 */

/** The five flight styles, plus the firmware card, in reading order. */
export type FlightStyleId =
  | 'cinematic'
  | 'freestyle'
  | 'racing'
  | 'tiny-whoop'
  | 'long-range'
  | 'firmware';

export type GuideStep = {
  readonly n: number;
  readonly titleAr: string;
  /** Where in the app this step is performed. */
  readonly screen: string;
  /** What the picture is proven to be showing. */
  readonly recommended: readonly string[];
  readonly sources: readonly string[];
  readonly note: string | null;
  /** True pixel size of this step's capture, so a frame can reserve its
   *  exact aspect ratio instead of guessing and cropping. */
  readonly width: number;
  readonly height: number;
};

/**
 * A verdict on a requirement this corner's steps do NOT change, so a
 * reader never has to wonder whether a setting was forgotten.
 */
export type GuideDecisionKind =
  | 'STEP' | 'ACTION' | 'PILOT_PREFERENCE' | 'KEEP_DEFAULT' | 'NOT_APPLICABLE';

export type GuideDecision = {
  readonly what: string;
  readonly kind: GuideDecisionKind;
  readonly detail: string;
  readonly source: string | null;
};

export type GuideCorner = {
  readonly id: FlightStyleId;
  /** 'FLIGHT_STYLE' or the firmware card, which is not a flight style. */
  readonly kind: string;
  readonly titleAr: string;
  readonly titleEn: string;
  readonly descriptionAr: string;
  readonly difficultyAr: string;
  readonly aircraft: readonly string[];
  readonly verification: string;
  readonly hardwareStatus: string;
  readonly steps: readonly GuideStep[];
  readonly decisions: readonly GuideDecision[];
  readonly warnings: readonly string[];
};

export const GUIDE_CORNERS: readonly GuideCorner[] = [
  {
    id: 'cinematic',
    kind: 'FLIGHT_STYLE',
    titleAr: 'الطيران السينمائي',
    titleEn: 'Cinematic',
    descriptionAr: 'طيران هادئ ومتصل، الهدف فيه أن تبدو اللقطة كأن كاميرا محمولة على ذراع.',
    difficultyAr: 'مبتدئ',
    aircraft: ['Cinewhoop', 'Cinelog', '5 إنش بكاميرا HD', '7 إنش للقطات الواسعة'],
    verification: 'SOFTWARE / REFERENCE VERIFIED',
    hardwareStatus: 'NOT VERIFIED — DEFERRED',
    steps: [
      {
        n: 1,
        titleAr: 'المستقبل',
        screen: 'المستقبل · بطاقة تنعيم الإشارة',
        recommended: ['90', '50'],
        sources: ['S1.1'],
        note: null,
        width: 708,
        height: 1138,
      },
      {
        n: 2,
        titleAr: 'إحساس العصا',
        screen: 'ضبط PID · بطاقة إحساس العصا',
        recommended: ['12', '15', '1 خيار محدَّد'],
        sources: ['S1.1', 'S1.13'],
        note: null,
        width: 708,
        height: 882,
      },
      {
        n: 3,
        titleAr: 'المحركات',
        screen: 'المحركات · إعدادات ESC',
        recommended: ['14', '1 خيار محدَّد', '1 مفتاح مفعّل'],
        sources: ['S1.11a', 'S1.10b'],
        note: null,
        width: 708,
        height: 3162,
      },
      {
        n: 4,
        titleAr: 'Dynamic Idle',
        screen: 'ضبط PID · بطاقة Dynamic Idle',
        recommended: ['35'],
        sources: ['S1.11a'],
        note: null,
        width: 708,
        height: 542,
      },
      {
        n: 5,
        titleAr: 'Failsafe',
        screen: 'Failsafe · إجراء المرحلة 2',
        recommended: ['1 خيار محدَّد'],
        sources: [],
        note: null,
        width: 632,
        height: 344,
      },
      {
        n: 6,
        titleAr: 'OSD',
        screen: 'OSD · بطاقة التنبيهات',
        recommended: ['-102 dBm'],
        sources: ['S1.1'],
        note: null,
        width: 708,
        height: 1002,
      },
    ],
    decisions: [
      {what: 'ترددا القطع (setpoint · الخانق)', kind: 'KEEP_DEFAULT', detail: 'اتركهما 0 — أي «تلقائي». الإعداد السينمائي الرسمي يضبط المعاملين التلقائيين ولا يلمس ترددي القطع.', source: 'S1.13'},
      {what: 'Rates', kind: 'PILOT_PREFERENCE', detail: 'لا توجد Rates رسمية للسينمائي. اختر ملفًا أبطأ من ملفك المعتاد وارفع expo قليلًا لتنعيم المنتصف — ولا نفرض رقمًا واحدًا لهذا النمط.', source: null},
      {what: 'قيم PID (P · I · D)', kind: 'KEEP_DEFAULT', detail: 'الإعدادان السينمائيان الرسميان لا يلمسان P أو I أو D إطلاقًا. النعومة تأتي من إحساس العصا والتنعيم، لا من خفض PID.', source: 'S1.1'},
      {what: 'الفلاتر (Gyro LPF · D-term LPF · Dynamic Notch)', kind: 'KEEP_DEFAULT', detail: 'اتبع ضبط منصتك. القيم المرجعية للسينمائي (سقف 750Hz لـ Cinelog، أدنى 125Hz لبناء نظيف) في قسم «اختياري»، والتطبيق لا يعدّلها إلا إذا أثبتت القراءة أن الميزة نشطة.', source: 'S1.11a'},
      {what: 'الأوضاع (Modes)', kind: 'PILOT_PREFERENCE', detail: 'مفتاح ARM إلزامي ويُضبط مرة واحدة لكل طائرة. ما بعده — Angle أو Beeper أو Turtle — تفضيلك.', source: null},
      {what: 'الطاقة والبطارية', kind: 'PILOT_PREFERENCE', detail: 'لا توجد حدود بطارية «سينمائية». اضبطها على حزمتك أنت: عدد الخلايا، وتحذير الخلية، والسعة.', source: null},
      {what: 'مرسل الفيديو (VTX)', kind: 'NOT_APPLICABLE', detail: 'لا يغيّره هذا النمط. اضبط القناة والطاقة مرة واحدة حسب مكانك وقوانينه.', source: null},
      {what: '`thrust_linear`', kind: 'NOT_APPLICABLE', detail: 'يضبطه الإعداد الرسمي حسب تردد ESC (0 عند 24k · 20 عند 48k · 40 عند 96k)، ولا يعرضه هذا التطبيق. يُضبط من سطر الأوامر أو بتطبيق الحزمة.', source: 'S1.11a'},
    ],
    warnings: ['**التنعيم العالي يعني تأخيرًا حقيقيًا في استجابة العصا.** الإعدادات الرسمية نفسها تحمل هذا التحذير حرفيًا (S1.6, S1.7). إن كنت ستطير بين عوائق ضيقة، ابدأ من 90 لا من 180.', '**لا تختبر إعدادًا جديدًا وأنت تصوّر لقطة قريبة من ناس أو أشياء.** جرّبه في مساحة مفتوحة أولًا.', '**Failsafe يُضبط قبل أول رحلة، لا بعدها.**'],
  },
  {
    id: 'freestyle',
    kind: 'FLIGHT_STYLE',
    titleAr: 'الطيران الحر',
    titleEn: 'Freestyle',
    descriptionAr: 'حركات وقلبات وتدفّق حول العوائق، باستجابة حادة بلا عصبية.',
    difficultyAr: 'متوسط',
    aircraft: ['5 إنش', '3–4 إنش', '7 إنش'],
    verification: 'SOFTWARE / REFERENCE VERIFIED',
    hardwareStatus: 'NOT VERIFIED — DEFERRED',
    steps: [
      {
        n: 1,
        titleAr: 'المستقبل',
        screen: 'المستقبل · بطاقة تنعيم الإشارة',
        recommended: ['50', '50'],
        sources: ['S1.3'],
        note: null,
        width: 708,
        height: 1138,
      },
      {
        n: 2,
        titleAr: 'إحساس العصا',
        screen: 'ضبط PID · بطاقة إحساس العصا',
        recommended: ['8', '15', '1 خيار محدَّد'],
        sources: ['S1.3', 'S1.13'],
        note: null,
        width: 708,
        height: 882,
      },
      {
        n: 3,
        titleAr: 'المحركات',
        screen: 'المحركات · إعدادات ESC',
        recommended: ['1 خيار محدَّد', '1 مفتاح مفعّل'],
        sources: ['S1.10b'],
        note: null,
        width: 708,
        height: 3162,
      },
      {
        n: 4,
        titleAr: 'Dynamic Idle',
        screen: 'ضبط PID · بطاقة Dynamic Idle',
        recommended: ['30'],
        sources: ['S1.10a–c'],
        note: null,
        width: 708,
        height: 542,
      },
      {
        n: 5,
        titleAr: 'Failsafe',
        screen: 'Failsafe · إجراء المرحلة 2',
        recommended: ['1 خيار محدَّد'],
        sources: [],
        note: null,
        width: 708,
        height: 420,
      },
      {
        n: 6,
        titleAr: 'OSD',
        screen: 'OSD · بطاقة التنبيهات',
        recommended: ['-98 dBm'],
        sources: ['S1.3'],
        note: null,
        width: 708,
        height: 1002,
      },
    ],
    decisions: [
      {what: 'ترددا القطع (setpoint · الخانق)', kind: 'KEEP_DEFAULT', detail: 'اتركهما 0 — أي «تلقائي». إعداد الحر الرسمي يضبط المعاملين التلقائيين فقط.', source: 'S1.13'},
      {what: 'Rates', kind: 'PILOT_PREFERENCE', detail: 'المكتبة الرسمية تعرض ثلاثة ملفات للنمط نفسه، وهذا في ذاته الجواب: لا يوجد رقم صحيح واحد. الخيارات الرسمية — RC rate 2 / expo 40 / super 80 · أو 3 / 35 / 105 · أو 25 / 45 / 108. ابدأ من الأول وارفع تدريجيًا.', source: 'S1.10b'},
      {what: 'قيم PID (P · I · D)', kind: 'KEEP_DEFAULT', detail: 'إعداد الحر الرسمي للرابط لا يلمس P أو I أو D. حزم الضبط تستعمل منزلقات simplified التي لا يعرضها التطبيق؛ لا تعدّل القيم يدويًا لملاحقتها.', source: 'S1.3'},
      {what: 'الفلاتر (Gyro LPF · D-term LPF · Dynamic Notch)', kind: 'KEEP_DEFAULT', detail: 'اتبع ضبط مقاسك. القيم المرجعية (سقف 400Hz وأدنى 90Hz لمقاس 3–5") في قسم «اختياري».', source: 'S1.10b'},
      {what: 'الأوضاع (Modes)', kind: 'PILOT_PREFERENCE', detail: 'مفتاح ARM إلزامي. Airmode و Turtle و Beeper تفضيلك.', source: null},
      {what: 'الطاقة والبطارية', kind: 'PILOT_PREFERENCE', detail: 'اضبطها على حزمتك: عدد الخلايا وتحذير الخلية والسعة. لا قيمة «حرة» رسمية.', source: null},
      {what: 'مرسل الفيديو (VTX)', kind: 'NOT_APPLICABLE', detail: 'لا يغيّره هذا النمط. اضبطه مرة واحدة حسب مكانك.', source: null},
      {what: '`thrust_linear`', kind: 'NOT_APPLICABLE', detail: '30 لمقاس 5" · 40 لمقاس 3–4" · 10 لمقاس 7" في الإعداد الرسمي، ولا يعرضه هذا التطبيق.', source: 'S1.10b'},
    ],
    warnings: ['**جلسة المحركات تدير المحركات فعلًا.** المراوح مفكوكة، دائمًا، بلا استثناء.', '**فلتر RPM يتطلب DShot ثنائي الاتجاه يعمل بشكل صحيح.** الإعدادات الرسمية تحمل تحذيرًا صريحًا: تشغيل ضبط يعتمد على فلتر RPM بدون فلترة RPM سليمة **قد يؤدي إلى حريق** (S1.8, S1.9). تحقق من أن قراءة RPM تصل قبل أن تطير.', '**بعد أي تغيير في الضبط: سلّح على الأرض واستمع.** يجب أن يكون الصوت نظيفًا بلا طحن. ثم حوّم وتحقق من حرارة المحركات. إن كان أي شيء غريبًا، لا تطر (S1.8, S1.9).', '**أوقف «Hardware ADC Filter» في راديو EdgeTX/OpenTX.** كل إعداد رابط رسمي يكرر هذا التحذير (S1.1–S1.7).'],
  },
  {
    id: 'racing',
    kind: 'FLIGHT_STYLE',
    titleAr: 'السباق',
    titleEn: 'Racing',
    descriptionAr: 'أقصر زمن حول مسار. كل شيء يُقاس بالتأخير.',
    difficultyAr: 'متقدم',
    aircraft: ['5 إنش على 6S', '5 إنش على 4S'],
    verification: 'SOFTWARE / REFERENCE VERIFIED',
    hardwareStatus: 'NOT VERIFIED — DEFERRED',
    steps: [
      {
        n: 1,
        titleAr: 'المستقبل',
        screen: 'المستقبل · بطاقة تنعيم الإشارة',
        recommended: ['25', '25'],
        sources: ['S1.4'],
        note: null,
        width: 708,
        height: 1138,
      },
      {
        n: 2,
        titleAr: 'إحساس العصا',
        screen: 'ضبط PID · بطاقة إحساس العصا',
        recommended: ['3', '18', '1 خيار محدَّد'],
        sources: ['S1.4'],
        note: null,
        width: 708,
        height: 882,
      },
      {
        n: 3,
        titleAr: 'المحركات',
        screen: 'المحركات · إعدادات ESC',
        recommended: ['1 خيار محدَّد', '1 مفتاح مفعّل'],
        sources: ['S1.9'],
        note: null,
        width: 708,
        height: 3162,
      },
      {
        n: 4,
        titleAr: 'Dynamic Idle',
        screen: 'ضبط PID · بطاقة Dynamic Idle',
        recommended: ['40'],
        sources: ['S1.9'],
        note: null,
        width: 708,
        height: 542,
      },
      {
        n: 5,
        titleAr: 'Failsafe',
        screen: 'Failsafe · إجراء المرحلة 2',
        recommended: ['1 خيار محدَّد'],
        sources: [],
        note: null,
        width: 708,
        height: 420,
      },
      {
        n: 6,
        titleAr: 'OSD',
        screen: 'OSD · بطاقة التنبيهات',
        recommended: ['-95 dBm'],
        sources: ['S1.4'],
        note: null,
        width: 708,
        height: 1002,
      },
      {
        n: 7,
        titleAr: 'مرسل الفيديو — قناتك ووضع الانتظار',
        screen: 'مرسل الفيديو · القناة والطاقة',
        recommended: ['2 خيار محدَّد', '1 مفتاح مفعّل'],
        sources: [],
        note: 'في السباق **النطاق والقناة ليسا اختيارك**، بل ما يخصصه لك المنظّم — واللقطة تعرض `Raceband` كمثال على ذلك، لا كتوصية. الحقل الذي يخصّك فعلًا هو **Pit Mode**: مفعّل هنا، أي أن المرسل صامت وأنت على خط الانطلاق، فلا تفسد فيديو من يطير الآن. أطفئه عند دورك. الجدول كله مقروء من متحكم الطيران، فما تراه هو ما يدعمه مرسلك أنت.',
        width: 708,
        height: 2398,
      },
    ],
    decisions: [
      {what: 'ترددا القطع (setpoint · الخانق)', kind: 'KEEP_DEFAULT', detail: 'اتركهما 0. إعداد السباق الرسمي يخفض المعاملين التلقائيين إلى 25 بدل استعمال ترددات قطع ثابتة.', source: 'S1.13'},
      {what: 'Rates', kind: 'PILOT_PREFERENCE', detail: 'لا توجد Rates رسمية باسم «سباق». المكتبة تعرض ملفات مؤلفين كخيارات لا كقاعدة. المبدأ: expo أقل من الحر، لأن الدقة حول المنتصف أهم من مدى الطرف — والرقم يبقى اختيارك.', source: null},
      {what: 'قيم PID (P · I · D)', kind: 'KEEP_DEFAULT', detail: 'إعداد السباق الرسمي يضبط PID عبر منزلقات simplified ثم `simplified_tuning apply`، وهي غير معروضة في التطبيق. لا تحاكِ النتيجة بتعديل P/I/D يدويًا.', source: 'S1.9'},
      {what: 'الفلاتر (Gyro LPF · D-term LPF · Dynamic Notch)', kind: 'KEEP_DEFAULT', detail: 'اتبع حزمة الضبط. القيم المرجعية (سقف 650Hz، أدنى 125Hz لبناء نظيف) في قسم «اختياري».', source: 'S1.9'},
      {what: 'الأوضاع (Modes)', kind: 'PILOT_PREFERENCE', detail: 'مفتاح ARM إلزامي. Turtle مفيد في السباق؛ بقية الأوضاع تفضيلك.', source: null},
      {what: 'الطاقة والبطارية', kind: 'PILOT_PREFERENCE', detail: 'اضبطها على حزمتك. السباق لا يفرض حدود بطارية، لكن تحذير الخلية يجب أن يصلك قبل نهاية اللفة لا بعدها.', source: null},
      {what: '`thrust_linear` · `tpa_*`', kind: 'NOT_APPLICABLE', detail: 'يضبطهما الإعداد الرسمي (thrust_linear 20 · tpa_rate 70 · tpa_breakpoint 1250) ولا يعرضهما هذا التطبيق.', source: 'S1.9'},
    ],
    warnings: ['**لا تشغّل مرسل الفيديو بلا هوائي.** قد يتلف المرسل خلال ثوانٍ.', '**في السباق المنظّم، القناة والطاقة ليستا اختيارك وحدك.** تشغيل قناة غير مخصصة لك يفسد فيديو طيار آخر أثناء طيرانه.', '**فلترة RPM إلزامية مع ضبط السباق.** الإعدادات الرسمية تقول صراحةً إن تشغيل هذا الضبط بدون فلترة RPM **قد يؤدي إلى حريق** (S1.8, S1.9).', '**سلّح على الأرض واستمع قبل أن تطير.** صوت نظيف بلا طحن، ثم تحويم وفحص حرارة المحركات. إن كان أي شيء غريبًا، لا تطر (S1.9).', '**ضبط السباق يفترض إطارًا مخدومًا.** أذرع مرتخية أو محركات متضررة تحوّل الضبط الحاد إلى اهتزاز.'],
  },
  {
    id: 'tiny-whoop',
    kind: 'FLIGHT_STYLE',
    titleAr: 'الوووب والطيران الداخلي',
    titleEn: 'Tiny Whoop / Indoor',
    descriptionAr: 'طائرة صغيرة بمراوح محمية تطير داخل الغرف. أصغر منصة وأكثرها اختلافًا.',
    difficultyAr: 'مبتدئ',
    aircraft: ['وووب 1S بلا فرش (65 مم)', 'وووب 2S'],
    verification: 'SOFTWARE / REFERENCE VERIFIED',
    hardwareStatus: 'NOT VERIFIED — DEFERRED',
    steps: [
      {
        n: 1,
        titleAr: 'المحركات',
        screen: 'المحركات · إعدادات ESC',
        recommended: ['12', '1 خيار محدَّد', '1 مفتاح مفعّل'],
        sources: ['S1.8'],
        note: null,
        width: 708,
        height: 3162,
      },
      {
        n: 2,
        titleAr: 'Dynamic Idle',
        screen: 'ضبط PID · بطاقة Dynamic Idle',
        recommended: ['120'],
        sources: ['S1.8'],
        note: null,
        width: 708,
        height: 542,
      },
      {
        n: 3,
        titleAr: 'إحساس العصا',
        screen: 'ضبط PID · بطاقة إحساس العصا',
        recommended: ['3', '18'],
        sources: ['S1.8'],
        note: null,
        width: 708,
        height: 882,
      },
      {
        n: 4,
        titleAr: 'الطاقة والبطارية',
        screen: 'الطاقة · حدود بطارية 1S',
        recommended: ['4.45 V', '450 mAh'],
        sources: ['S1.8'],
        note: null,
        width: 708,
        height: 1110,
      },
      {
        n: 5,
        titleAr: 'منحنى الخانق',
        screen: 'ضبط PID · منحنى وحدّ الخانق',
        recommended: ['30', '65', '30'],
        sources: ['S1.8'],
        note: null,
        width: 708,
        height: 1218,
      },
      {
        n: 6,
        titleAr: 'Failsafe',
        screen: 'Failsafe · إجراء المرحلة 2',
        recommended: ['1 خيار محدَّد'],
        sources: [],
        note: null,
        width: 708,
        height: 420,
      },
    ],
    decisions: [
      {what: 'المستقبل · تنعيم الإشارة', kind: 'KEEP_DEFAULT', detail: 'إعداد الوووب الرسمي **لا يضمّن** ملف الرابط، فالتنعيم يبقى على أصله: معاملان تلقائيان 30/30 وترددا قطع 0. لا تغيّرهما لهذا النمط.', source: 'S1.13'},
      {what: 'Rates', kind: 'PILOT_PREFERENCE', detail: 'الإعداد الرسمي يعرض ملف rates كخيار غير معلَّم، لا كقاعدة. الوووب يميل إلى yaw أعلى لأن دورانه بطيء بطبعه — والرقم اختيارك.', source: null},
      {what: 'قيم PID (P · I · D)', kind: 'KEEP_DEFAULT', detail: 'إعداد الوووب الرسمي يضبط PID عبر منزلقات simplified، وهي غير معروضة في التطبيق. لا تعدّل P/I/D يدويًا.', source: 'S1.8'},
      {what: 'الفلاتر', kind: 'KEEP_DEFAULT', detail: 'الإعداد الرسمي يطفئ Gyro LPF1 و Dynamic Notch ويعتمد على فلتر RPM وحده. لا يسمح التطبيق بتفعيل أو تعطيل Dynamic Notch، وهذا هو السلوك الصحيح هنا.', source: 'S1.8'},
      {what: 'وضع الطيران: Acro · Angle · Horizon', kind: 'PILOT_PREFERENCE', detail: '**Acro صحيح تمامًا للوووب، وليس Angle إلزاميًا.** Angle مساعدة تعلّم مفيدة داخل الغرف؛ ضعها على مفتاح إن أردت الرجوع إليها، أو اتركها.', source: null},
      {what: 'Airmode', kind: 'PILOT_PREFERENCE', detail: 'الإعداد الرسمي يقول إن إطفاءه أفضل أداءً في الطيران الداخلي، ويعرض ذلك كخيار غير معلَّم. للأكروبات في مساحة كبيرة، ضعه على مفتاح.', source: 'S1.8'},
      {what: 'تعويض هبوط الجهد (`vbat_sag_compensation`)', kind: 'NOT_APPLICABLE', detail: 'موصى به في الإعداد الرسمي (خيار معلَّم، القيمة 100) لأن خلية 1S تهبط بشدة تحت الحمل — لكن **هذا التطبيق لا يعرضه**. يُضبط من سطر الأوامر أو بتطبيق الحزمة الرسمية.', source: 'S1.8'},
      {what: 'OSD', kind: 'PILOT_PREFERENCE', detail: 'لا يوجد رقم رسمي للوووب. إن كان لديك OSD، ابدأ من إنذار RSSI dBm عند −98 وعدّله بعد رحلة داخل مبناك — الجدران تغيّر الرقم أكثر من النمط.', source: null},
      {what: 'مرسل الفيديو (VTX)', kind: 'PILOT_PREFERENCE', detail: 'الطيران الداخلي لا يحتاج طاقة عالية؛ ابدأ من أقل مستوى يعطيك صورة نظيفة.', source: null},
      {what: '`cpu_late_limit_permille`', kind: 'NOT_APPLICABLE', detail: 'يضبطه الإعداد الرسمي عند 15، ولا يعرضه التطبيق. غيابه لا يمنع الطيران.', source: 'S1.8'},
    ],
    warnings: ['**حجم الطائرة لا يجعل جلسة المحركات آمنة.** المحركات تدور فعلًا. المراوح مفكوكة، حتى على وووب.', '**فلترة RPM إلزامية مع هذا الضبط.** الإعداد الرسمي يقول حرفيًا إن تشغيله بدونها **قد يؤدي إلى حريق** (S1.8).', '**سلّح على الأرض واستمع.** صوت نظيف بلا طحن، ثم تحويم وفحص حرارة المحركات. إن كان أي شيء غريبًا، لا تطر (S1.8).', '**4.45V لخلايا 1S الحديثة فقط.** ضبط هذا الرقم على بطارية 4.2V تقليدية يعني أن تحذير الجهد لن يصل في وقته.', '**الطيران الداخلي يعني ناسًا وأشياء على مسافة أمتار.** جرّب أي إعداد جديد في أوسع مساحة متاحة أولًا.'],
  },
  {
    id: 'long-range',
    kind: 'FLIGHT_STYLE',
    titleAr: 'المدى الطويل',
    titleEn: 'Long Range',
    descriptionAr: 'الطيران خارج مدى البصر. النمط الوحيد الذي يكون فيه فقد الإشارة حدثًا متوقعًا لا حادثًا.',
    difficultyAr: 'متقدم',
    aircraft: ['7 إنش', '6 إنش', '5 إنش خفيفة بمراوح كبيرة'],
    verification: 'SOFTWARE / REFERENCE VERIFIED',
    hardwareStatus: 'NOT VERIFIED — DEFERRED',
    steps: [
      {
        n: 1,
        titleAr: 'المنافذ',
        screen: 'المنافذ · منفذ GPS',
        recommended: [],
        sources: [],
        note: null,
        width: 780,
        height: 2448,
      },
      {
        n: 2,
        titleAr: 'المستقبل',
        screen: 'المستقبل · المصدر و RSSI',
        recommended: ['10', '15'],
        sources: ['S1.5'],
        note: null,
        width: 708,
        height: 1138,
      },
      {
        n: 3,
        titleAr: 'GPS',
        screen: 'GPS · التفعيل و Home والدقة',
        recommended: [],
        sources: [],
        note: null,
        width: 780,
        height: 6512,
      },
      {
        n: 4,
        titleAr: 'GPS Rescue',
        screen: 'Failsafe · معاملات GPS Rescue',
        recommended: ['30 م', '7.5 م/ث', '1.5 م/ث', '8', '2 خيار محدَّد'],
        sources: ['S1.12d'],
        note: null,
        width: 708,
        height: 3342,
      },
      {
        n: 5,
        titleAr: 'الأوضاع',
        screen: 'الأوضاع · GPS Rescue على مفتاح',
        recommended: [],
        sources: [],
        note: null,
        width: 780,
        height: 4470,
      },
      {
        n: 6,
        titleAr: 'الطاقة والبطارية',
        screen: 'الطاقة · مثال 6S',
        recommended: ['3.50 V'],
        sources: [],
        note: null,
        width: 708,
        height: 1110,
      },
      {
        n: 7,
        titleAr: 'مرسل الفيديو — الطاقة ومستوياتها الحقيقية',
        screen: 'مرسل الفيديو · القناة والطاقة',
        recommended: ['2 خيار محدَّد'],
        sources: [],
        note: '**لا رقم رسمي هنا، والقانون هو من يقرر.** ما تعرضه اللقطة هو **أعلى مستوى يعلنه هذا المرسل** (600) — لتعرف أين تقرأ المستويات المتاحة على عتادك، لا لتنسخ الرقم. القاعدة الوحيدة في هذا الدليل: أعلى طاقة **تسمح بها قوانين مكانك**، لا أعلى طاقة موجودة.\n\nومفعَّل هنا أيضًا **طاقة منخفضة عند DISARM**: المدى الطويل يعني وقتًا طويلًا مسلَّحًا وطاقة عالية، فخفض الطاقة تلقائيًا بعد نزع التسليح يقلّل حرارة المرسل وأنت واقف. `[C]`',
        width: 708,
        height: 2398,
      },
      {
        n: 8,
        titleAr: 'OSD',
        screen: 'OSD · إنذارات السلامة',
        recommended: ['-100 dBm', '60%'],
        sources: [],
        note: null,
        width: 708,
        height: 1002,
      },
      {
        n: 9,
        titleAr: 'إحساس العصا',
        screen: 'ضبط PID · بطاقة إحساس العصا',
        recommended: ['10', '0', '1 خيار محدَّد'],
        sources: ['S1.5'],
        note: null,
        width: 708,
        height: 882,
      },
    ],
    decisions: [
      {what: 'المحركات و Dynamic Idle', kind: 'ACTION', detail: 'فعّل Bidirectional DShot، واضبط عدد الأقطاب على محركك، واضبط Dynamic Idle على **30** (×100 rpm) لمقاس 7". من شاشة المحركات وشاشة ضبط PID.', source: 'S1.10c'},
      {what: 'Rates', kind: 'PILOT_PREFERENCE', detail: 'لا توجد Rates رسمية للمدى الطويل. المبدأ: أبطأ من ملفك المعتاد — أنت تطير في خط مستقيم طويلًا لا تنعطف بحدة. والرقم اختيارك.', source: null},
      {what: 'قيم PID (P · I · D)', kind: 'KEEP_DEFAULT', detail: 'إعداد المدى الطويل الرسمي يغيّر إحساس العصا والتنعيم فقط، ولا يلمس P أو I أو D.', source: 'S1.5'},
      {what: 'الفلاتر', kind: 'KEEP_DEFAULT', detail: 'اتبع ضبط مقاسك. القيمة المرجعية لمقاس 7" هي أدنى فلتر ديناميكي 40Hz، لأن الهيكل الطويل يرنّ عند تردد أخفض.', source: 'S1.10c'},
      {what: 'قراءة جودة الرابط (LQ) و RSSI بوحدة dBm', kind: 'NOT_APPLICABLE', detail: '**غير موجودتين في عقد MSP إطلاقًا**، فلا يستطيع أي تطبيق MSP عرضهما حيًّا. تراهما في نظارتك عبر OSD؛ التطبيق يضبط عتبة الإنذار فقط (الخطوة 8).', source: null},
      {what: 'نوع التثبيت (2D/3D) و HDOP/VDOP', kind: 'NOT_APPLICABLE', detail: 'بروتوكول الاتصال مع المتحكم يرسل **بت تثبيت واحدًا و PDOP وحده** — لا 2D/3D ولا HDOP/VDOP. التطبيق يعرض PDOP بالاسم الصحيح ولا يخترع بديلًا. اسم الأمر نفسه في `_meta/sources.md` § S2.2.', source: null},
    ],
    warnings: ['**GPS Rescue ليس ضمانًا.** هو إجراء يعمل عندما تكون كل حلقات السلسلة صحيحة. حلقة واحدة خاطئة — بوصلة غير معايرة، أقمار قليلة، Home غير مثبَّت — تعني طائرة تطير بثقة في الاتجاه الخطأ.', '**اختبر الإنقاذ وأنت ترى الطائرة.** أول تجربة لإجراء العودة يجب أن تكون على ارتفاع آمن، في مساحة مفتوحة، ضمن مدى بصرك. لا تجعل أول تجربة هي الحالة الحقيقية.', '**البطارية تُحسب للعودة.** طائرة تنقطع في أبعد نقطة ببطارية كافية للذهاب فقط لن تصل.', '**لا تشغّل مرسل الفيديو بلا هوائي.** قد يتلف خلال ثوانٍ. وهذا أخطر في المدى الطويل لأنك ترفع الطاقة.', '**`السماح بالتسليح دون GPS Fix` مطفأ لسبب.** تشغيله يعني تسليحًا بلا نقطة عودة معروفة.', '**الرابط البطيء ليس للطيران الحر.** الإعداد الرسمي يحذّر من هذا نصًّا (S1.5). لا تطر أكروبات على وضع 15Hz.'],
  },
  {
    id: 'firmware',
    kind: 'PREREQUISITE',
    titleAr: 'البرنامج الثابت',
    titleEn: 'Firmware',
    descriptionAr: 'ما يجب أن يكون صحيحًا في متحكم طيرانك قبل أن يعني أي دليل نمط شيئًا.',
    difficultyAr: 'متوسط',
    aircraft: ['أي طائرة تعمل ببرنامج ثابت متوافق مع MSP'],
    verification: 'SOFTWARE VERIFIED',
    hardwareStatus: 'NOT VERIFIED — DEFERRED',
    steps: [
      {
        n: 1,
        titleAr: 'اللوحة والإصدار وخيارات البناء',
        screen: 'تحديث البرنامج الثابت · المرحلة 1: اللوحة والبناء',
        recommended: [],
        sources: [],
        note: 'الشاشة مرحلتان: **1 اللوحة والبناء**، ثم **2 التحقق والتفليش**. لا تنتقل إلى الثانية قبل أن تختار لوحة وإصدارًا.\n\nفي اللقطة اللوحة مختارة (`SPEEDYBEEF405V3`) والإصدار مختار (`4.6.0`)، ولهذا ظهرت **تهيئة البناء**: بروتوكول الراديو و Telemetry و OSD والمحركات. **هذه هي الخطوة التي تقرر ما سيوجد في لوحتك بعد التحديث** — ما لا تختاره هنا لن يكون موجودًا مهما بحثت عنه لاحقًا في الإعدادات.',
        width: 780,
        height: 5860,
      },
      {
        n: 2,
        titleAr: 'بوابة الأمان قبل التفليش',
        screen: 'تحديث البرنامج الثابت · المرحلة 2 · بطاقة بوابة الأمان',
        recommended: ['2 مفتاح مفعّل'],
        sources: [],
        note: 'المفتاحان في هذه البطاقة ليسا تذكيرًا — التفليش لا يبدأ قبل تفعيلهما، ولا تُتجاوَز البطاقة ضمنيًا حتى مع «Flash on connect». فعّلهما بعد أن تفعل ما يقولانه، لا قبله.',
        width: 732,
        height: 528,
      },
      {
        n: 3,
        titleAr: 'الحزم الجاهزة',
        screen: 'الحزم الجاهزة · المكتبة الرسمية',
        recommended: [],
        sources: ['S1'],
        note: 'لاحظ **الحزم المتوافقة (5)** — العدد ليس كل ما في المكتبة، بل ما يوافق إصدار **لوحتك أنت**، والإصدار مقروء من المتحكم لا مكتوب يدويًا. وسم «رسمية» بجانب كل حزمة هو حالة `OFFICIAL`.',
        width: 780,
        height: 2400,
      },
    ],
    decisions: [
      {what: 'إعدادات الطيران', kind: 'NOT_APPLICABLE', detail: 'هذه ليست بطاقة نمط طيران. بعد التحديث، افتح ركن نمطك واتبعه من خطوته الأولى.', source: null},
      {what: 'النسخة الاحتياطية قبل التحديث', kind: 'ACTION', detail: 'فعّل خيار النسخ الاحتياطي قبل بدء التفليش. التحديث يمسح كل إعداداتك، بما فيها Failsafe و GPS Rescue والمعايرة.', source: null},
      {what: 'ترتيب ما بعد التحديث', kind: 'ACTION', detail: 'المنافذ ← المستقبل ← المحركات ← الأوضاع (مفتاح ARM أولًا) ← Failsafe ← ثم دليل نمطك.', source: null},
    ],
    warnings: ['**التحديث يمسح كل إعداداتك.** بما فيها Failsafe و GPS Rescue ومعايرة البطارية وربط المفاتيح. النسخة الاحتياطية ليست احتياطًا زائدًا — هي الفرق بين إعادة ضبط ودقيقتين.', '**لا تحدّث بمراوح مركّبة.** أبدًا.', '**انقطاع الاتصال أثناء الكتابة قد يترك اللوحة بلا برنامج ثابت صالح.** استعمل كابلًا تثق به، ولا تحرّك الجهاز أثناء الكتابة.', '**بعد التحديث، إعدادات Failsafe عادت إلى أصلها.** أعد ضبطها قبل أول رحلة.'],
  },
];

/** Flight styles only - the firmware card is a technical section. */
export const FLIGHT_STYLES: readonly GuideCorner[] =
  GUIDE_CORNERS.filter(corner => corner.kind === 'FLIGHT_STYLE');

export function findCorner(id: string): GuideCorner | undefined {
  return GUIDE_CORNERS.find(corner => corner.id === id);
}
