/**
 * GENERATED by docs/flight-guides/_tools/write-app-content.mjs.
 * Do not edit by hand: the reviewed source is docs/flight-guides/, and
 * this file is rewritten from it. Change a value there, run the tool.
 */

/**
 * THE STEP PICTURES - Metro/Jest resolution.
 *
 * require() of a .png registers a real bundled asset, exactly as
 * src/ui/brand/brandLogoSource.ts does for the logo. tsconfig.web.json
 * excludes this file; Vite resolves the .web sibling instead.
 *
 * The files are NOT copied into src/. They are the reviewed captures in
 * docs/flight-guides/<style>/images/, and a second copy would be a
 * second thing to keep true.
 */

import type {ImageSourcePropType} from 'react-native';

export const GUIDE_STEP_IMAGES: Readonly<Record<string, ImageSourcePropType>> = {
  'cinematic/1': require('../../../docs/flight-guides/cinematic/images/1-receiver-smoothing.png') as ImageSourcePropType,
  'cinematic/2': require('../../../docs/flight-guides/cinematic/images/2-pid-feel.png') as ImageSourcePropType,
  'cinematic/3': require('../../../docs/flight-guides/cinematic/images/3-motors.png') as ImageSourcePropType,
  'cinematic/4': require('../../../docs/flight-guides/cinematic/images/4-dynamic-idle.png') as ImageSourcePropType,
  'cinematic/5': require('../../../docs/flight-guides/cinematic/images/5-failsafe.png') as ImageSourcePropType,
  'cinematic/6': require('../../../docs/flight-guides/cinematic/images/6-osd-alarms.png') as ImageSourcePropType,
  'freestyle/1': require('../../../docs/flight-guides/freestyle/images/1-receiver-smoothing.png') as ImageSourcePropType,
  'freestyle/2': require('../../../docs/flight-guides/freestyle/images/2-pid-feel.png') as ImageSourcePropType,
  'freestyle/3': require('../../../docs/flight-guides/freestyle/images/3-motors.png') as ImageSourcePropType,
  'freestyle/4': require('../../../docs/flight-guides/freestyle/images/4-dynamic-idle.png') as ImageSourcePropType,
  'freestyle/5': require('../../../docs/flight-guides/freestyle/images/5-failsafe.png') as ImageSourcePropType,
  'freestyle/6': require('../../../docs/flight-guides/freestyle/images/6-osd-alarms.png') as ImageSourcePropType,
  'racing/1': require('../../../docs/flight-guides/racing/images/1-receiver-smoothing.png') as ImageSourcePropType,
  'racing/2': require('../../../docs/flight-guides/racing/images/2-pid-feel.png') as ImageSourcePropType,
  'racing/3': require('../../../docs/flight-guides/racing/images/3-motors.png') as ImageSourcePropType,
  'racing/4': require('../../../docs/flight-guides/racing/images/4-dynamic-idle.png') as ImageSourcePropType,
  'racing/5': require('../../../docs/flight-guides/racing/images/5-failsafe.png') as ImageSourcePropType,
  'racing/6': require('../../../docs/flight-guides/racing/images/6-osd-alarms.png') as ImageSourcePropType,
  'racing/7': require('../../../docs/flight-guides/racing/images/7-vtx.png') as ImageSourcePropType,
  'tiny-whoop/1': require('../../../docs/flight-guides/tiny-whoop/images/1-motors.png') as ImageSourcePropType,
  'tiny-whoop/2': require('../../../docs/flight-guides/tiny-whoop/images/2-dynamic-idle.png') as ImageSourcePropType,
  'tiny-whoop/3': require('../../../docs/flight-guides/tiny-whoop/images/3-pid-feel.png') as ImageSourcePropType,
  'tiny-whoop/4': require('../../../docs/flight-guides/tiny-whoop/images/4-power.png') as ImageSourcePropType,
  'tiny-whoop/5': require('../../../docs/flight-guides/tiny-whoop/images/5-throttle-curve.png') as ImageSourcePropType,
  'tiny-whoop/6': require('../../../docs/flight-guides/tiny-whoop/images/6-failsafe.png') as ImageSourcePropType,
  'long-range/1': require('../../../docs/flight-guides/long-range/images/1-ports.png') as ImageSourcePropType,
  'long-range/2': require('../../../docs/flight-guides/long-range/images/2-receiver-cutoffs.png') as ImageSourcePropType,
  'long-range/3': require('../../../docs/flight-guides/long-range/images/3-gps.png') as ImageSourcePropType,
  'long-range/4': require('../../../docs/flight-guides/long-range/images/4-gps-rescue.png') as ImageSourcePropType,
  'long-range/5': require('../../../docs/flight-guides/long-range/images/5-modes.png') as ImageSourcePropType,
  'long-range/6': require('../../../docs/flight-guides/long-range/images/6-power.png') as ImageSourcePropType,
  'long-range/7': require('../../../docs/flight-guides/long-range/images/7-vtx.png') as ImageSourcePropType,
  'long-range/8': require('../../../docs/flight-guides/long-range/images/8-osd-alarms.png') as ImageSourcePropType,
  'long-range/9': require('../../../docs/flight-guides/long-range/images/9-pid-feel.png') as ImageSourcePropType,
  'firmware/1': require('../../../docs/flight-guides/firmware/images/1-flasher-board.png') as ImageSourcePropType,
  'firmware/2': require('../../../docs/flight-guides/firmware/images/2-flasher-safety.png') as ImageSourcePropType,
  'firmware/3': require('../../../docs/flight-guides/firmware/images/3-presets.png') as ImageSourcePropType,
};
