/**
 * GENERATED by docs/flight-guides/_tools/write-app-content.mjs.
 * Do not edit by hand: the reviewed source is docs/flight-guides/, and
 * this file is rewritten from it. Change a value there, run the tool.
 */

/**
 * THE STEP PICTURES - browser resolution.
 *
 * Vite resolves this file instead of guideImages.ts and serves each
 * capture as a hashed static asset: the exact committed bytes, decoded
 * by the browser, downloaded only when the corner that shows them is
 * opened.
 */

import type {ImageSourcePropType} from 'react-native';

import cinematic1 from '../../../docs/flight-guides/cinematic/images/1-receiver-smoothing.png';
import cinematic2 from '../../../docs/flight-guides/cinematic/images/2-pid-feel.png';
import cinematic3 from '../../../docs/flight-guides/cinematic/images/3-motors.png';
import cinematic4 from '../../../docs/flight-guides/cinematic/images/4-dynamic-idle.png';
import cinematic5 from '../../../docs/flight-guides/cinematic/images/5-failsafe.png';
import cinematic6 from '../../../docs/flight-guides/cinematic/images/6-osd-alarms.png';
import freestyle1 from '../../../docs/flight-guides/freestyle/images/1-receiver-smoothing.png';
import freestyle2 from '../../../docs/flight-guides/freestyle/images/2-pid-feel.png';
import freestyle3 from '../../../docs/flight-guides/freestyle/images/3-motors.png';
import freestyle4 from '../../../docs/flight-guides/freestyle/images/4-dynamic-idle.png';
import freestyle5 from '../../../docs/flight-guides/freestyle/images/5-failsafe.png';
import freestyle6 from '../../../docs/flight-guides/freestyle/images/6-osd-alarms.png';
import racing1 from '../../../docs/flight-guides/racing/images/1-receiver-smoothing.png';
import racing2 from '../../../docs/flight-guides/racing/images/2-pid-feel.png';
import racing3 from '../../../docs/flight-guides/racing/images/3-motors.png';
import racing4 from '../../../docs/flight-guides/racing/images/4-dynamic-idle.png';
import racing5 from '../../../docs/flight-guides/racing/images/5-failsafe.png';
import racing6 from '../../../docs/flight-guides/racing/images/6-osd-alarms.png';
import racing7 from '../../../docs/flight-guides/racing/images/7-vtx.png';
import tinyWhoop1 from '../../../docs/flight-guides/tiny-whoop/images/1-motors.png';
import tinyWhoop2 from '../../../docs/flight-guides/tiny-whoop/images/2-dynamic-idle.png';
import tinyWhoop3 from '../../../docs/flight-guides/tiny-whoop/images/3-pid-feel.png';
import tinyWhoop4 from '../../../docs/flight-guides/tiny-whoop/images/4-power.png';
import tinyWhoop5 from '../../../docs/flight-guides/tiny-whoop/images/5-throttle-curve.png';
import tinyWhoop6 from '../../../docs/flight-guides/tiny-whoop/images/6-failsafe.png';
import longRange1 from '../../../docs/flight-guides/long-range/images/1-ports.png';
import longRange2 from '../../../docs/flight-guides/long-range/images/2-receiver-cutoffs.png';
import longRange3 from '../../../docs/flight-guides/long-range/images/3-gps.png';
import longRange4 from '../../../docs/flight-guides/long-range/images/4-gps-rescue.png';
import longRange5 from '../../../docs/flight-guides/long-range/images/5-modes.png';
import longRange6 from '../../../docs/flight-guides/long-range/images/6-power.png';
import longRange7 from '../../../docs/flight-guides/long-range/images/7-vtx.png';
import longRange8 from '../../../docs/flight-guides/long-range/images/8-osd-alarms.png';
import longRange9 from '../../../docs/flight-guides/long-range/images/9-pid-feel.png';
import firmware1 from '../../../docs/flight-guides/firmware/images/1-flasher-board.png';
import firmware2 from '../../../docs/flight-guides/firmware/images/2-flasher-safety.png';
import firmware3 from '../../../docs/flight-guides/firmware/images/3-presets.png';

export const GUIDE_STEP_IMAGES: Readonly<Record<string, ImageSourcePropType>> = {
  'cinematic/1': {uri: cinematic1},
  'cinematic/2': {uri: cinematic2},
  'cinematic/3': {uri: cinematic3},
  'cinematic/4': {uri: cinematic4},
  'cinematic/5': {uri: cinematic5},
  'cinematic/6': {uri: cinematic6},
  'freestyle/1': {uri: freestyle1},
  'freestyle/2': {uri: freestyle2},
  'freestyle/3': {uri: freestyle3},
  'freestyle/4': {uri: freestyle4},
  'freestyle/5': {uri: freestyle5},
  'freestyle/6': {uri: freestyle6},
  'racing/1': {uri: racing1},
  'racing/2': {uri: racing2},
  'racing/3': {uri: racing3},
  'racing/4': {uri: racing4},
  'racing/5': {uri: racing5},
  'racing/6': {uri: racing6},
  'racing/7': {uri: racing7},
  'tiny-whoop/1': {uri: tinyWhoop1},
  'tiny-whoop/2': {uri: tinyWhoop2},
  'tiny-whoop/3': {uri: tinyWhoop3},
  'tiny-whoop/4': {uri: tinyWhoop4},
  'tiny-whoop/5': {uri: tinyWhoop5},
  'tiny-whoop/6': {uri: tinyWhoop6},
  'long-range/1': {uri: longRange1},
  'long-range/2': {uri: longRange2},
  'long-range/3': {uri: longRange3},
  'long-range/4': {uri: longRange4},
  'long-range/5': {uri: longRange5},
  'long-range/6': {uri: longRange6},
  'long-range/7': {uri: longRange7},
  'long-range/8': {uri: longRange8},
  'long-range/9': {uri: longRange9},
  'firmware/1': {uri: firmware1},
  'firmware/2': {uri: firmware2},
  'firmware/3': {uri: firmware3},
};
