export type {
  Spec as UsbSerialTransportSpec,
  UsbSerialDeviceDescriptor,
  SerialDataBits,
  SerialStopBits,
  SerialParity,
  SerialFlowControl,
  SerialConfiguration,
  UsbSerialDataEvent,
  UsbSerialSessionDetachedEvent,
  UsbSerialErrorEvent,
  UsbDeviceHotplugEvent,
  FirmwareFileSelection,
  DfuDeviceDescriptor,
  DfuFlashProgressEvent,
} from './NativeUsbSerialTransport';
