/* eslint-disable no-bitwise -- hand-composed wire words; the shifts ARE the
 * field offsets being pinned. */
/**
 * HAND-AUTHORED LED WIRE VECTORS.
 *
 * Every word and every byte below was worked out from the firmware header's
 * field offsets with a pencil, NOT produced by this repository's encoder. A
 * fixture generated by the code under test proves only that the code agrees
 * with itself, which is exactly the check that cannot catch a field at the
 * wrong offset. The little-endian expansion used to build the longer frames
 * is a local four-line helper for the same reason.
 *
 * Test-only. Nothing in `src/` outside a test imports this file.
 */

/** Independent LE expansion. Deliberately not the production encoder. */
function u32le(word: number): readonly number[] {
  return [word & 0xff, (word >>> 8) & 0xff, (word >>> 16) & 0xff, (word >>> 24) & 0xff];
}

function u16le(value: number): readonly number[] {
  return [value & 0xff, (value >>> 8) & 0xff];
}

export function bytes(values: readonly number[]): Uint8Array {
  return Uint8Array.from(values);
}

/* ------------------------------------------------------------------ *
 * F1 - one entry with every field distinguishable
 * ------------------------------------------------------------------ */

/**
 * x=13, y=6, base function 1, overlays {0,3,6} plus RESERVED BIT 8,
 * colour 11, directions {0,3,5}.
 *
 * Worked by hand, field by field:
 *
 *   y  = 6                            ->        0x00000006
 *   x  = 13   << 4                    ->        0x000000D0
 *   fn = 1    << 8                    ->        0x00000100
 *   ov = 0x149 (bits 0,3,6,8) << 12   ->        0x00149000
 *   col= 11   << 22                   ->        0x02C00000
 *   dir= 0x29 (bits 0,3,5)    << 26   ->        0xA4000000
 *                                        -----------------
 *                                              0xA6D491D6
 *
 * The reserved overlay bit is the point of this fixture: a decoder that
 * masks the overlay field down to its seven known bits produces 0x49 instead
 * of 0x149 and this vector catches it.
 */
export const F1_ENTRY_WORD = 0xa6d491d6;
export const F1_ENTRY_BYTES = bytes(u32le(F1_ENTRY_WORD));
export const F1_EXPECTED = Object.freeze({
  x: 13,
  y: 6,
  baseFunction: 1,
  overlayMask: 0x149,
  colorIndex: 11,
  directionMask: 0x29,
});

/* ------------------------------------------------------------------ *
 * F2 - an unknown base function
 * ------------------------------------------------------------------ */

/**
 * x=1, y=2, base function 14. Ten values are defined; the nibble holds
 * sixteen. 14 must survive as 14 - not clamped, not mapped to COLOUR, not
 * rejected.
 *
 *   y = 2, x = 1 << 4 = 0x10, fn = 14 << 8 = 0xE00  ->  0x00000E12
 */
export const F2_UNKNOWN_FUNCTION_WORD = 0x00000e12;
export const F2_UNKNOWN_FUNCTION_BYTES = bytes(u32le(F2_UNKNOWN_FUNCTION_WORD));

/* ------------------------------------------------------------------ *
 * F3 - a gap: terminator at index 1, configured entries after it
 * ------------------------------------------------------------------ */

/**
 *   index 0  x=0 y=1 fn=0 colour=1   ->  0x00400001
 *   index 1  all zero                ->  0x00000000   <- firmware stops here
 *   index 2  x=2 y=3 fn=2            ->  0x00000223
 *   index 3  x=4 y=5 fn=3            ->  0x00000345
 *
 * Effective count is 1. Indexes 2 and 3 are configured, transmitted, and
 * completely dead.
 */
export const F3_GAP_WORDS: readonly number[] = Object.freeze([0x00400001, 0x00000000, 0x00000223, 0x00000345]);

/* ------------------------------------------------------------------ *
 * F4 - two LEDs at one coordinate
 * ------------------------------------------------------------------ */

/**
 *   index 0  x=4 y=6 fn=1  ->  0x00000146
 *   index 1  x=9 y=2 colour=3 -> 0x00C00092
 *   index 2  x=4 y=6 fn=2  ->  0x00000246
 *
 * Indexes 0 and 2 share (4,6). The firmware permits this without complaint;
 * the reference configurator loses one of them on load because it keys its
 * grid by coordinate. Both must survive here.
 */
export const F4_DUPLICATE_WORDS: readonly number[] = Object.freeze([0x00000146, 0x00c00092, 0x00000246]);

/* ------------------------------------------------------------------ *
 * F5 - the corners of the coordinate space
 * ------------------------------------------------------------------ */

/** x=15, y=15, base function 0, nothing else. 0xFF and no more. */
export const F5_MAX_COORDINATE_WORD = 0x000000ff;

/**
 * Every field at its maximum: x=15, y=15, fn=15, overlays=0x3FF,
 * colour=15, directions=0x3F.
 *
 *   0xFF | (15<<8) | (0x3FF<<12) | (15<<22) | (0x3F<<26) = 0xFFFFFFFF
 *
 * The result being exactly all-ones is itself the proof that the six fields
 * tile the 32-bit word with no gap and no overlap.
 */
export const F5_ALL_FIELDS_MAX_WORD = 0xffffffff;

/* ------------------------------------------------------------------ *
 * F6 / F7 / F8 - complete strip GET frames
 * ------------------------------------------------------------------ */

/**
 * A distinct, non-terminator word for array slot `i`.
 *
 * `y` and `x` differ by one modulo sixteen, so they are never both zero and
 * the word can never collide with the terminator - no fallback needed, and
 * deliberately none written, because a `|| default` here would be the very
 * pattern these fixtures exist to catch.
 */
function fillerWord(i: number): number {
  const y = (i + 1) & 0x0f;
  const x = (i + 2) & 0x0f;
  const fn = (i % 10) & 0x0f;
  const colour = (i * 3 + 1) & 0x0f;
  return (y | (x << 4) | (fn << 8) | (colour << 22)) >>> 0;
}

function stripFrame(count: number, advanced: number, profile: number): Uint8Array {
  const out: number[] = [];
  for (let i = 0; i < count; i++) out.push(...u32le(fillerWord(i)));
  out.push(advanced, profile);
  return bytes(out);
}

/** 32 entries, advanced board, profile 2. 32*4 + 2 = 130 bytes. */
export const F6_STRIP_32 = stripFrame(32, 1, 2);
/** 64 entries, advanced board, profile 1. 64*4 + 2 = 258 bytes. */
export const F7_STRIP_64 = stripFrame(64, 1, 1);
/** 20 entries - neither 32 nor 64, and structurally perfectly valid. */
export const F8_STRIP_20 = stripFrame(20, 0, 0);

export const F6_EXPECTED_WORDS: readonly number[] = Object.freeze(
  Array.from({length: 32}, (_unused, i) => fillerWord(i)),
);
export const F7_EXPECTED_WORDS: readonly number[] = Object.freeze(
  Array.from({length: 64}, (_unused, i) => fillerWord(i)),
);
export const F8_EXPECTED_WORDS: readonly number[] = Object.freeze(
  Array.from({length: 20}, (_unused, i) => fillerWord(i)),
);

/* ------------------------------------------------------------------ *
 * F9 - a 64-byte palette, every slot different
 * ------------------------------------------------------------------ */

/** Sixteen slots whose hue, whiteness and value are all distinct per slot. */
export const F9_PALETTE_EXPECTED: readonly {hue: number; whiteness: number; value: number}[] = Object.freeze(
  Array.from({length: 16}, (_unused, slot) => ({
    hue: (slot * 23 + 1) % 360,
    whiteness: (slot * 17 + 5) & 0xff,
    value: (slot * 13 + 200) & 0xff,
  })),
);

export const F9_PALETTE_BYTES = bytes(
  F9_PALETTE_EXPECTED.flatMap((color) => [...u16le(color.hue), color.whiteness, color.value]),
);

/* ------------------------------------------------------------------ *
 * F10 - the three anchors that kill a conventional-HSV reading
 * ------------------------------------------------------------------ */

/**
 * Straight out of the firmware's own default table, comments included:
 *
 *   BLACK {0,0,0}      "LED is off"
 *   WHITE {0,255,255}  "for white, S must be 255 and V must be 255"
 *   RED   {0,0,255}    "for full colour S must be 0 and V must be 255"
 *
 * Zero in the middle field is the MOST vivid value and 255 is white. Any code
 * that treats that field as ordinary saturation renders red as grey and white
 * as red, and these three vectors are what catches it.
 */
export const F10_HSV_ANCHORS = Object.freeze({
  black: Object.freeze({hue: 0, whiteness: 0, value: 0}),
  white: Object.freeze({hue: 0, whiteness: 255, value: 255}),
  red: Object.freeze({hue: 0, whiteness: 0, value: 255}),
});

/** The same three as the first three slots of a full palette frame. */
export const F10_ANCHOR_PALETTE_BYTES = bytes([
  ...u16le(0), 0, 0, // black
  ...u16le(0), 255, 255, // white
  ...u16le(0), 0, 255, // red
  ...Array.from({length: 13 * 4}, () => 0),
]);

/* ------------------------------------------------------------------ *
 * F11 - a complete 144-byte mode-colour frame
 * ------------------------------------------------------------------ */

/**
 * The firmware's fixed emission order: 6 modes x 6 directions, then eleven
 * special slots under mode 6, then one aux tuple as (7, 0, channel).
 *
 * Values step by 5 (coprime with 16), so within any run of sixteen tuples no
 * value repeats and none of them coincides with its own slot number - a
 * decoder that reported the slot byte as the value would fail immediately.
 */
export const F11_MODECOLOR_EXPECTED: readonly {mode: number; slot: number; value: number}[] = Object.freeze(
  (() => {
    const tuples: {mode: number; slot: number; value: number}[] = [];
    let n = 0;
    const nextValue = (): number => (n++ * 5 + 1) % 16;
    for (let mode = 0; mode < 6; mode++) {
      for (let slot = 0; slot < 6; slot++) tuples.push({mode, slot, value: nextValue()});
    }
    for (let slot = 0; slot < 11; slot++) tuples.push({mode: 6, slot, value: nextValue()});
    tuples.push({mode: 7, slot: 0, value: nextValue()});
    return tuples;
  })(),
);

export const F11_MODECOLOR_BYTES = bytes(
  F11_MODECOLOR_EXPECTED.flatMap((tuple) => [tuple.mode, tuple.slot, tuple.value]),
);

/* ------------------------------------------------------------------ *
 * F12 - the five MSP2 value bytes
 * ------------------------------------------------------------------ */

/**
 * brightness 0x25, rainbowDelta 0x0102, rainbowFreq 0x0403 - five bytes with
 * no two alike, so a byte-order slip anywhere in the frame changes at least
 * one decoded field.
 */
export const F12_CONFIG_VALUES_BYTES = bytes([0x25, 0x02, 0x01, 0x03, 0x04]);
export const F12_CONFIG_VALUES_EXPECTED = Object.freeze({
  brightness: 0x25,
  rainbowDelta: 0x0102,
  rainbowFreq: 0x0403,
});

/**
 * All three genuinely zero. The reference tab's `value || default` turns this
 * frame into brightness 50 / freq 1 and then writes the invention back to the
 * board; a decoder that does the same fails against this vector.
 */
export const F12_ALL_ZERO_BYTES = bytes([0, 0, 0, 0, 0]);
