import type {MspRequestOptions} from '../../../core/protocol/mspClient';
import type {MspFrame} from '../../../core/protocol/mspTypes';
import type {MspTelemetryScheduler} from '../../../core/protocol/telemetry';
import {MSP_BOXIDS, MSP_BUILD_INFO, MSP_EEPROM_WRITE, MSP_FAILSAFE_CONFIG, MSP_RXFAIL_CONFIG, MSP_SET_FAILSAFE_CONFIG, MSP_SET_RXFAIL_CONFIG, MSP_STATUS_EX} from '../../../core/protocol/msp/commands/mspCommands';
import {createFailsafeConfigurationDraft} from '../../../core/state/failsafeConfigurationModel';
import type {MspFailsafeSnapshot} from '../../../core/protocol/msp/decoding/decodeFailsafe';
import type {MspIdentificationState} from './MspSessionCoordinator';
import {FailsafeConfigurationController, type FailsafeSessionCoordinator} from './FailsafeConfigurationController';

type Script = {payload: Uint8Array} | {reject: unknown}; const EMPTY = new Uint8Array(0); const key = {sessionId: 'failsafe-fc', generation: 5} as const;
class FakeClient {readonly calls: Array<{command: number; payload: Uint8Array; options: MspRequestOptions}> = []; private readonly scripts = new Map<number, Script[]>(); getEpoch() {return 1;} enqueue(command: number, ...scripts: Script[]) {this.scripts.set(command, [...(this.scripts.get(command) ?? []), ...scripts]);} async request(command: number, payload: Uint8Array, options: MspRequestOptions): Promise<MspFrame> {this.calls.push({command, payload, options}); const script = this.scripts.get(command)?.shift(); if (script !== undefined && 'reject' in script) throw script.reject; return {protocolVersion: 'v1', wireFormat: options.wireFormat, direction: 'response', command, flags: 0, payload: script?.payload ?? EMPTY};}}
function main(delay = 15): Uint8Array {return Uint8Array.from([delay, 60, 232, 3, 0, 100, 0, 1]);}
function rx(changed = false): Uint8Array {return Uint8Array.from([0, 220, 5, 0, 220, 5, 0, 220, 5, 0, 232, 3, changed ? 2 : 1, changed ? 226 : 220, changed ? 4 : 5]);}
function build(): Uint8Array {const data = new Uint8Array(30); const view = new DataView(data.buffer); view.setUint16(26, 16412, true); return data;}
function status(armed: boolean): Uint8Array {return Uint8Array.from([0, 0, 0, 0, 0, 0, armed ? 1 : 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 29, 0, 0, 0, 0, 0]);}
function identification(): MspIdentificationState {return {status: 'SUCCEEDED', identity: {firmware: {identifier: 'BTFL', knownFamily: 'BETAFLIGHT'}, apiVersion: {mspProtocolVersion: 0, apiVersionMajor: 1, apiVersionMinor: 47}, board: {}}} as MspIdentificationState;}
function scheduler(): MspTelemetryScheduler {return {acquirePauseLease: jest.fn(() => ({release: jest.fn()})), discardPendingDemands: jest.fn(), waitUntilIdle: jest.fn(() => Promise.resolve()), requestRefresh: jest.fn()} as unknown as MspTelemetryScheduler;}
function harness() {const client = new FakeClient(); const telemetry = scheduler(); const coordinator: FailsafeSessionCoordinator = {getOwnershipState: () => 'ACTIVE', getIdentificationState: () => identification(), getSessionKey: sessionId => ({sessionId, generation: 5}), getActiveMspClient: () => client, getTelemetryScheduler: () => telemetry, getMspRecoveryState: () => 'READY'}; return {client, telemetry, controller: new FailsafeConfigurationController({coordinator, appStateOwner: {getPhase: () => 'ACTIVE'}, isMotorTestActive: () => false})};}
function enqueueSnapshot(client: FakeClient, delay = 15, changed = false) {client.enqueue(MSP_FAILSAFE_CONFIG, {payload: main(delay)}); client.enqueue(MSP_RXFAIL_CONFIG, {payload: rx(changed)}); client.enqueue(MSP_BUILD_INFO, {payload: build()});}
async function loadOriginal(h: ReturnType<typeof harness>): Promise<MspFailsafeSnapshot> {enqueueSnapshot(h.client); const result = await h.controller.load(key); if (result.kind !== 'LOADED') throw new Error(result.kind); return result.snapshot;}

describe('FailsafeConfigurationController', () => {
  it('loads main, per-channel and GPS build evidence together', async () => {const h = harness(); const snapshot = await loadOriginal(h); expect(snapshot.channels).toHaveLength(5); expect(snapshot.supportsGpsRescue).toBe(true); expect(h.telemetry.acquirePauseLease).toHaveBeenCalledTimes(1);});
  it('blocks writes while ARMED', async () => {const h = harness(); const original = await loadOriginal(h); enqueueSnapshot(h.client); h.client.enqueue(MSP_BOXIDS, {payload: Uint8Array.from([0])}); h.client.enqueue(MSP_STATUS_EX, {payload: status(true)}); const draft = {...createFailsafeConfigurationDraft(original), delayDeciseconds: 20}; await expect(h.controller.save(key, original, draft)).resolves.toEqual({kind: 'REJECTED', reason: 'FC_ARMED'}); expect(h.client.calls.map(call => call.command)).not.toContain(MSP_SET_FAILSAFE_CONFIG);});
  it('writes changed groups once, persists once and verifies readback', async () => {const h = harness(); const original = await loadOriginal(h); enqueueSnapshot(h.client); h.client.enqueue(MSP_BOXIDS, {payload: Uint8Array.from([0])}); h.client.enqueue(MSP_STATUS_EX, {payload: status(false)}); h.client.enqueue(MSP_SET_FAILSAFE_CONFIG, {payload: EMPTY}); h.client.enqueue(MSP_SET_RXFAIL_CONFIG, {payload: EMPTY}); h.client.enqueue(MSP_EEPROM_WRITE, {payload: EMPTY}); enqueueSnapshot(h.client, 20, true); const base = createFailsafeConfigurationDraft(original); const draft = {...base, delayDeciseconds: 20, channels: [...base.channels.slice(0, 4), {mode: 2 as const, value: 1250}]}; await expect(h.controller.save(key, original, draft)).resolves.toEqual(expect.objectContaining({kind: 'SAVED_VERIFIED'})); expect(h.client.calls.filter(call => call.command === MSP_SET_FAILSAFE_CONFIG)).toHaveLength(1); expect(h.client.calls.filter(call => call.command === MSP_SET_RXFAIL_CONFIG)).toHaveLength(1); expect(h.client.calls.filter(call => call.command === MSP_EEPROM_WRITE)).toHaveLength(1);});
});
