import {MSP_BATTERY_STATE, decodeBatteryState, type MspTelemetryScheduler} from '../../../core';
import {BATTERY_TELEMETRY_POLL_ID, mspSessionCoordinator, type SetupUiSessionKey} from './MspSessionCoordinator';

export const POWER_BATTERY_POLL_ID = 'power-battery-live';
export const POWER_BATTERY_POLL_INTERVAL_MS = 200;
interface Registration {readonly generation: number; readonly scheduler: MspTelemetryScheduler; references: number; readonly unregister: () => void; readonly releaseDefaultSuppression: () => void}
const active = new Map<string, Registration>();
export function acquirePowerTelemetry(key: SetupUiSessionKey): () => void {const scheduler = mspSessionCoordinator.getTelemetryScheduler(key.sessionId); const currentKey = mspSessionCoordinator.getSessionKey(key.sessionId); if (scheduler === undefined || currentKey?.generation !== key.generation) return () => {}; const existing = active.get(key.sessionId); if (existing?.generation === key.generation && existing.scheduler === scheduler) {existing.references += 1; return releaseFor(key, existing);} if (existing !== undefined) {existing.unregister(); existing.releaseDefaultSuppression();} const registration: Registration = {generation: key.generation, scheduler, references: 1, unregister: scheduler.registerPoll({id: POWER_BATTERY_POLL_ID, command: MSP_BATTERY_STATE, intervalMs: POWER_BATTERY_POLL_INTERVAL_MS, staleAfterMs: 1200, priority: 1, decode: decodeBatteryState}), releaseDefaultSuppression: scheduler.acquirePollSuppression(BATTERY_TELEMETRY_POLL_ID)}; active.set(key.sessionId, registration); return releaseFor(key, registration);}
function releaseFor(key: SetupUiSessionKey, registration: Registration): () => void {let released = false; return () => {if (released) return; released = true; const current = active.get(key.sessionId); if (current !== registration) return; current.references -= 1; if (current.references > 0) return; current.unregister(); current.releaseDefaultSuppression(); active.delete(key.sessionId);};}
