import {MSP_BATTERY_CONFIG, MSP_CURRENT_METER_CONFIG, MSP_EEPROM_WRITE, MSP_SET_BATTERY_CONFIG, MSP_SET_CURRENT_METER_CONFIG, MSP_SET_VOLTAGE_METER_CONFIG, MSP_STATUS_EX, MSP_VOLTAGE_METER_CONFIG, BoxIdsAcquisition, MspOperationOutcomeUnknownError, createMspOperationCoordinator, createPowerConfigurationDraft, decodeBatteryConfiguration, decodeCurrentMeterConfiguration, decodeStatusExDiagnostics, decodeVoltageMeterConfiguration, encodeChangedPowerConfiguration, powerDraftsEqual, powerSnapshotsEqual, validatePowerDraft, type BoxIdsOwnerIdentity, type MspPowerConfigurationSnapshot, type MspRequester, type MspTelemetryScheduler, type PowerConfigurationDraft, type PowerWriteGroup} from '../../../core';
import type {MspClientState} from '../../../core/protocol/mspClient'; import {deriveArmedState} from '../../../core/state/armingBlockers'; import {isMotorTestSessionActive} from './motorTestCapability'; import {mspSessionCoordinator, type MspIdentificationState, type MspSessionOwnershipState, type SetupUiSessionKey} from './MspSessionCoordinator'; import {setupAppStateTelemetryOwner, type SetupAppStatePhase} from './setupAppStateTelemetryOwner'; import {acquireMotorConfigurationInterlock, MotorConfigurationTransactionInProgressError} from './motorConfigurationInterlock';
import {isSupportedConfigurationApi} from './betaflightApiSupport';
const EMPTY = new Uint8Array(0); const DEFINITELY_NOT_SENT = new Set(['MSP_ENCODE_FAILED', 'MSP_QUEUE_FULL', 'MSP_TRANSPORT_QUEUE_FULL', 'MSP_RECOVERY_REQUIRED', 'MSP_RECOVERING', 'MSP_REMOTE_ERROR']);
interface PowerClient extends MspRequester {getEpoch(): number}
export interface PowerSessionCoordinator {getOwnershipState(sessionId: string): MspSessionOwnershipState; getIdentificationState(sessionId: string): MspIdentificationState; getSessionKey(sessionId: string): SetupUiSessionKey | undefined; getActiveMspClient(sessionId: string): PowerClient | undefined; getTelemetryScheduler(sessionId: string): MspTelemetryScheduler | undefined; getMspRecoveryState(sessionId: string): MspClientState | undefined}
export interface PowerAppStateOwner {getPhase(): SetupAppStatePhase}
export type PowerBlockReason = 'DISCONNECTED' | 'IDENTIFYING' | 'UNSUPPORTED_FIRMWARE' | 'APP_BACKGROUNDED' | 'LINK_RECOVERING' | 'FC_ARMED' | 'ARMED_STATE_UNKNOWN' | 'MOTOR_TEST_ACTIVE' | 'CONFIGURATION_BUSY' | 'STALE_BASE' | 'INVALID_CONFIGURATION';
export type PowerSaveStage = {readonly group: PowerWriteGroup; readonly id?: number} | {readonly group: 'EEPROM'};
export type PowerLoadOutcome = {readonly kind: 'LOADED'; readonly snapshot: MspPowerConfigurationSnapshot} | {readonly kind: 'REJECTED'; readonly reason: PowerBlockReason} | {readonly kind: 'SESSION_ENDED'} | {readonly kind: 'FAILED'; readonly error: unknown};
export type PowerSaveOutcome = {readonly kind: 'NO_CHANGES'; readonly snapshot: MspPowerConfigurationSnapshot} | {readonly kind: 'SAVED_VERIFIED'; readonly snapshot: MspPowerConfigurationSnapshot} | {readonly kind: 'SAVED_UNVERIFIED'; readonly error: unknown} | {readonly kind: 'REJECTED'; readonly reason: PowerBlockReason} | {readonly kind: 'UNCONFIRMED'; readonly stage: PowerSaveStage} | {readonly kind: 'SESSION_ENDED'} | {readonly kind: 'FAILED'; readonly error: unknown};
export interface PowerConfigurationControllerOptions {readonly coordinator?: PowerSessionCoordinator; readonly appStateOwner?: PowerAppStateOwner; readonly isMotorTestActive?: (sessionId: string) => boolean}
class PowerPreflightError extends Error {constructor(readonly reason: PowerBlockReason) {super(`Power preflight rejected: ${reason}`); this.name = 'PowerPreflightError';}}
interface AmbiguousPowerCause {readonly kind: 'POWER_AMBIGUOUS_WRITE'; readonly stage: PowerSaveStage}
class AmbiguousPowerWriteError extends MspOperationOutcomeUnknownError {constructor(error: unknown, stage: PowerSaveStage) {super(Object.freeze({kind: 'POWER_AMBIGUOUS_WRITE', stage, error}));}}
function errorCode(error: unknown): string | undefined {return error !== null && typeof error === 'object' && 'code' in error ? String((error as {code: unknown}).code) : undefined;} function ambiguousCause(value: unknown): value is AmbiguousPowerCause {return value !== null && typeof value === 'object' && 'kind' in value && value.kind === 'POWER_AMBIGUOUS_WRITE';}

export class PowerConfigurationController {
  private readonly coordinator: PowerSessionCoordinator; private readonly appStateOwner: PowerAppStateOwner; private readonly isMotorTestActive: (sessionId: string) => boolean; private readonly boxIds = new Map<string, {client: PowerClient; acquisition: BoxIdsAcquisition}>();
  constructor(options: PowerConfigurationControllerOptions = {}) {this.coordinator = options.coordinator ?? mspSessionCoordinator; this.appStateOwner = options.appStateOwner ?? setupAppStateTelemetryOwner; this.isMotorTestActive = options.isMotorTestActive ?? isMotorTestSessionActive;}
  async load(key: SetupUiSessionKey): Promise<PowerLoadOutcome> {const captured = this.capture(key); if ('reason' in captured) return {kind: 'REJECTED', reason: captured.reason}; const {client, scheduler, epoch} = captured; let interlock; try {interlock = acquireMotorConfigurationInterlock(client);} catch (error) {return error instanceof MotorConfigurationTransactionInProgressError ? {kind: 'REJECTED', reason: 'CONFIGURATION_BUSY'} : {kind: 'FAILED', error};} try {const result = await this.operations(key.sessionId, client, scheduler).execute<MspPowerConfigurationSnapshot>({id: `power:load:${key.sessionId}:${key.generation}`, sessionEffect: 'KEEP_SESSION', validate: context => context.clientState === 'READY' ? {allowed: true} : {allowed: false, error: new PowerPreflightError('LINK_RECOVERING')}, execute: async requester => {this.assertLive(key, client, epoch); return this.readSnapshot(requester);}}); if (result.status === 'SUCCEEDED') return {kind: 'LOADED', snapshot: result.result}; if (result.status === 'SESSION_ENDED' || result.status === 'OUTCOME_UNKNOWN') return {kind: 'SESSION_ENDED'}; return result.error instanceof PowerPreflightError ? {kind: 'REJECTED', reason: result.error.reason} : {kind: 'FAILED', error: result.error};} finally {interlock.release();}}
  async save(key: SetupUiSessionKey, original: MspPowerConfigurationSnapshot, draft: PowerConfigurationDraft): Promise<PowerSaveOutcome> {if (powerDraftsEqual(createPowerConfigurationDraft(original), draft)) return {kind: 'NO_CHANGES', snapshot: original}; if (validatePowerDraft(draft, original).length > 0) return {kind: 'REJECTED', reason: 'INVALID_CONFIGURATION'}; const captured = this.capture(key); if ('reason' in captured) return {kind: 'REJECTED', reason: captured.reason}; const {client, scheduler, epoch} = captured; let interlock; try {interlock = acquireMotorConfigurationInterlock(client);} catch (error) {return error instanceof MotorConfigurationTransactionInProgressError ? {kind: 'REJECTED', reason: 'CONFIGURATION_BUSY'} : {kind: 'FAILED', error};} try {const acquisition = this.boxIdsFor(key.sessionId, client); const identity: BoxIdsOwnerIdentity = {physicalGeneration: key.generation, mspEpoch: epoch}; const result = await this.operations(key.sessionId, client, scheduler).execute<{snapshot?: MspPowerConfigurationSnapshot; readbackError?: unknown}>({id: `power:save:${key.sessionId}:${key.generation}`, sessionEffect: 'KEEP_SESSION', validate: context => context.clientState === 'READY' ? {allowed: true} : {allowed: false, error: new PowerPreflightError('LINK_RECOVERING')}, execute: async requester => {this.assertLive(key, client, epoch); const fresh = await this.readSnapshot(requester); if (!powerSnapshotsEqual(fresh, original)) throw new PowerPreflightError('STALE_BASE'); await this.assertDisarmed(key, client, epoch, requester, acquisition, identity); for (const write of encodeChangedPowerConfiguration(original, draft)) {const command = write.group === 'BATTERY_CONFIG' ? MSP_SET_BATTERY_CONFIG : write.group === 'VOLTAGE_METER_CONFIG' ? MSP_SET_VOLTAGE_METER_CONFIG : MSP_SET_CURRENT_METER_CONFIG; await this.writeOnce(requester, command, write.payload, {group: write.group, id: write.id});} await this.writeOnce(requester, MSP_EEPROM_WRITE, EMPTY, {group: 'EEPROM'}); try {const snapshot = await this.readSnapshot(requester); if (!powerDraftsEqual(createPowerConfigurationDraft(snapshot), draft)) throw new Error('Power readback does not match saved values.'); return {snapshot};} catch (error) {return {readbackError: error};}}}); if (result.status === 'SUCCEEDED') return result.result.snapshot !== undefined ? {kind: 'SAVED_VERIFIED', snapshot: result.result.snapshot} : {kind: 'SAVED_UNVERIFIED', error: result.result.readbackError}; if (result.status === 'OUTCOME_UNKNOWN') return ambiguousCause(result.reason) ? {kind: 'UNCONFIRMED', stage: result.reason.stage} : {kind: 'SESSION_ENDED'}; if (result.status === 'SESSION_ENDED') return {kind: 'SESSION_ENDED'}; return result.error instanceof PowerPreflightError ? {kind: 'REJECTED', reason: result.error.reason} : {kind: 'FAILED', error: result.error};} finally {interlock.release();}}
  private async writeOnce(requester: MspRequester, command: number, payload: Uint8Array, stage: PowerSaveStage): Promise<void> {try {await requester.request(command, payload, {wireFormat: 'v1'});} catch (error) {const code = errorCode(error); if (code !== undefined && DEFINITELY_NOT_SENT.has(code)) throw error; throw new AmbiguousPowerWriteError(error, stage);}}
  private capture(key: SetupUiSessionKey): {client: PowerClient; scheduler: MspTelemetryScheduler; epoch: number} | {reason: PowerBlockReason} {if (this.appStateOwner.getPhase() !== 'ACTIVE') return {reason: 'APP_BACKGROUNDED'}; if (this.isMotorTestActive(key.sessionId)) return {reason: 'MOTOR_TEST_ACTIVE'}; const identification = this.coordinator.getIdentificationState(key.sessionId); if (identification.status === 'IDLE' || identification.status === 'RUNNING') return {reason: 'IDENTIFYING'}; if (!isSupportedConfigurationApi(identification)) return {reason: 'UNSUPPORTED_FIRMWARE'}; const client = this.coordinator.getActiveMspClient(key.sessionId); const scheduler = this.coordinator.getTelemetryScheduler(key.sessionId); if (this.coordinator.getOwnershipState(key.sessionId) !== 'ACTIVE' || this.coordinator.getSessionKey(key.sessionId)?.generation !== key.generation || client === undefined || scheduler === undefined) return {reason: 'DISCONNECTED'}; if (this.coordinator.getMspRecoveryState(key.sessionId) !== 'READY') return {reason: 'LINK_RECOVERING'}; return {client, scheduler, epoch: client.getEpoch()};}
  private assertLive(key: SetupUiSessionKey, client: PowerClient, epoch: number): void {if (this.appStateOwner.getPhase() !== 'ACTIVE') throw new PowerPreflightError('APP_BACKGROUNDED'); if (this.isMotorTestActive(key.sessionId)) throw new PowerPreflightError('MOTOR_TEST_ACTIVE'); if (this.coordinator.getOwnershipState(key.sessionId) !== 'ACTIVE' || this.coordinator.getSessionKey(key.sessionId)?.generation !== key.generation || this.coordinator.getActiveMspClient(key.sessionId) !== client || client.getEpoch() !== epoch) throw new PowerPreflightError('DISCONNECTED'); if (this.coordinator.getMspRecoveryState(key.sessionId) !== 'READY') throw new PowerPreflightError('LINK_RECOVERING');}
  private operations(sessionId: string, client: PowerClient, scheduler: MspTelemetryScheduler) {return createMspOperationCoordinator(client, scheduler, {captureCurrent: () => this.coordinator.getSessionKey(sessionId)}, {getContext: () => ({clientState: this.coordinator.getMspRecoveryState(sessionId) ?? 'DISCONNECTED', isArmed: false})});}
  private boxIdsFor(sessionId: string, client: PowerClient): BoxIdsAcquisition {const existing = this.boxIds.get(sessionId); if (existing?.client === client) return existing.acquisition; const acquisition = new BoxIdsAcquisition(client); this.boxIds.set(sessionId, {client, acquisition}); return acquisition;}
  private async assertDisarmed(key: SetupUiSessionKey, client: PowerClient, epoch: number, requester: MspRequester, acquisition: BoxIdsAcquisition, identity: BoxIdsOwnerIdentity): Promise<void> {const mapping = await acquisition.acquire(identity, () => this.coordinator.getSessionKey(key.sessionId)?.generation === key.generation && this.coordinator.getActiveMspClient(key.sessionId) === client && client.getEpoch() === epoch); this.assertLive(key, client, epoch); if (mapping.kind !== 'READY') throw new PowerPreflightError('ARMED_STATE_UNKNOWN'); const frame = await requester.request(MSP_STATUS_EX, EMPTY, {wireFormat: 'v1'}); const status = decodeStatusExDiagnostics(frame.payload); const armed = deriveArmedState(status.flightModeFlagsLow32, status.readiness.extraFlightModeFlagBytes, mapping.permanentIds); if (armed === 'ARMED') throw new PowerPreflightError('FC_ARMED'); if (armed !== 'DISARMED' || status.readiness.malformedTail) throw new PowerPreflightError('ARMED_STATE_UNKNOWN'); this.assertLive(key, client, epoch);}
  private async readSnapshot(requester: MspRequester): Promise<MspPowerConfigurationSnapshot> {const battery = decodeBatteryConfiguration((await requester.request(MSP_BATTERY_CONFIG, EMPTY, {wireFormat: 'v1'})).payload); const voltageMeters = decodeVoltageMeterConfiguration((await requester.request(MSP_VOLTAGE_METER_CONFIG, EMPTY, {wireFormat: 'v1'})).payload); const currentMeters = decodeCurrentMeterConfiguration((await requester.request(MSP_CURRENT_METER_CONFIG, EMPTY, {wireFormat: 'v1'})).payload); return Object.freeze({battery, voltageMeters, currentMeters});}
}
export const powerConfigurationController = new PowerConfigurationController();
