export type {
  MspWireFormat,
  MspProtocolVersion,
  MspDirection,
  MspFrame,
  MspDiagnostic,
} from './mspTypes';
export {
  MSP_V2_FRAME_ID,
  MSP_MAX_PAYLOAD_BYTES_DEFAULT,
  MSP_PROTOCOL_SIZE_FIELD_CEILING,
  MSP_PARTIAL_FRAME_TIMEOUT_MS_DEFAULT,
} from './mspTypes';

export { MSP_DIAGNOSTIC_CODES } from './mspErrors';
export type {
  MspDiagnosticCode,
  MspDiagnosticDetailMap,
  MspDiagnosticDetail,
} from './mspErrors';

export {
  xorChecksumStep,
  xorChecksum,
  crc8DvbS2Step,
  crc8DvbS2,
} from './mspChecksum';

export { encode } from './mspEncoder';
export type { MspEncodeOptions } from './mspEncoder';

export { createMspStreamParser } from './mspStreamParser';
export type {
  MspStreamParser,
  MspStreamParserOptions,
  MspIngestEvent,
  MspIngestResult,
} from './mspStreamParser';

export type {
  MspTransport,
  MspTransportError,
  MspTransportSessionDetachedEvent,
  MspTransportUnsubscribe,
} from './mspTransport';

export { MSP_CLIENT_ERROR_CODES } from './mspClientErrorCodes';
export type { MspClientErrorCode } from './mspClientErrorCodes';

export {
  MspClient,
  MspClientError,
  MSP_CLIENT_MAX_PENDING_REQUESTS_DEFAULT,
  MSP_RESPONSE_TIMEOUT_MILLIS,
} from './mspClient';
export type {
  MspClientState,
  MspRequestPhase,
  MspRequestOptions,
  MspClientOptions,
  MspClientDiagnosticEvent,
} from './mspClient';

export {
  MSP_API_VERSION,
  MSP_FC_VARIANT,
  MSP_BUILD_INFO,
  MSP_BOARD_INFO,
  MSP_ATTITUDE,
  MSP_BATTERY_STATE,
  MSP_RAW_GPS,
  MSP_COMP_GPS,
  MSP_GPS_CONFIG,
  MSP_GPS_SV_INFO,
  MSP_ANALOG,
  MSP_STATUS_EX,
  MSP_TX_INFO,
  MSP_BOXIDS,
  MSP_ACC_CALIBRATION,
  MSP_MAG_CALIBRATION,
  MSP_REBOOT,
  MSP_NAME,
  MSP_SET_NAME,
  STATUS_SENSOR_GPS_BIT,
  MSP_FEATURE_CONFIG,
  MSP_SET_FEATURE_CONFIG,
  MSP_RX_CONFIG,
  MSP_SET_RX_CONFIG,
  MSP_RSSI_CONFIG,
  MSP_SET_RSSI_CONFIG,
  MSP_RX_MAP,
  MSP_SET_RX_MAP,
  MSP_ARMING_CONFIG,
  MSP_SET_ARMING_CONFIG,
  MSP_BEEPER_CONFIG,
  MSP_SET_BEEPER_CONFIG,
  MSP2_GET_TEXT,
  MSP2_SET_TEXT,
  MSP_MIXER_CONFIG,
  MSP_ADVANCED_CONFIG,
  MSP_MOTOR,
  MSP_RC,
  MSP_RC_TUNING,
  MSP_PID,
  MSP_FILTER_CONFIG,
  MSP_PID_ADVANCED,
  MSP_SET_FILTER_CONFIG,
  MSP_SET_PID_ADVANCED,
  MSP_SET_PID,
  MSP_SET_RC_TUNING,
  MSP_MOTOR_3D_CONFIG,
  MSP_RC_DEADBAND,
  MSP_MOTOR_CONFIG,
  MSP_MOTOR_TELEMETRY,
  MSP_BLACKBOX_CONFIG,
  MSP_SET_BLACKBOX_CONFIG,
  MSP_DATAFLASH_SUMMARY,
  MSP_SDCARD_SUMMARY,
  MSP2_MOTOR_OUTPUT_REORDERING,
  MSP2_SET_MOTOR_OUTPUT_REORDERING,
  MSP2_SEND_DSHOT_COMMAND,
  MSP_SET_MIXER_CONFIG,
  MSP_SET_ADVANCED_CONFIG,
  MSP_SET_MOTOR_3D_CONFIG,
  MSP_SET_RC_DEADBAND,
  MSP_SET_MOTOR_CONFIG,
  MSP_SET_GPS_CONFIG,
  MSP_EEPROM_WRITE,
  MSP_VTX_CONFIG,
  MSP2_COMMON_SERIAL_CONFIG,
  MSP2_COMMON_SET_SERIAL_CONFIG,
  MSP_SENSOR_CONFIG,
  MSP_SET_SENSOR_CONFIG,
  MSP_SENSOR_ALIGNMENT,
  MSP_SET_SENSOR_ALIGNMENT,
  MSP_COMPASS_CONFIG,
  MSP_SET_COMPASS_CONFIG,
  MSP_ACC_TRIM,
  MSP_SET_ACC_TRIM,
  MSP2_SENSOR_CONFIG_ACTIVE,
  MSP2_GYRO_SENSOR_ACTIVE,
  MSP_SONAR_ALTITUDE,
  modelSensorHardware,
  sensorHardwareDefaultIndex,
  sensorHardwareIndices,
  sensorHardwareNoneIndex,
  decodeSensorConfig,
  NOT_AVAILABLE_IN_THIS_CONTRACT,
  SENSOR_CONFIG_CONTRACT_BYTES,
  SENSOR_CONFIG_MIN_BYTES,
  decodeSensorAlignment,
  gyroIndicesFromBitmask,
  modelSensorAlignment,
  ALIGN_CUSTOM_RAW,
  ALIGN_DEFAULT_RAW,
  SENSOR_ALIGNMENT_PAYLOAD_BYTES,
  decodeSensorConfigActive,
  SENSOR_CONFIG_ACTIVE_BYTES,
  SENSOR_NOT_AVAILABLE,
  SENSOR_NOT_AVAILABLE_RAW,
  decodeGyroSensorActive,
  decodeAccTrim,
  ACC_TRIM_PAYLOAD_BYTES,
  decodeCompassConfig,
  COMPASS_CONFIG_PAYLOAD_BYTES,
  encodeSensorConfig,
  sensorConfigContractFor,
  sensorConfigWriteFrom,
  encodeSensorAlignment,
  CUSTOM_ALIGNMENT_DECIDEGREE_LIMIT,
  SENSOR_ALIGNMENT_WRITE_BASE_BYTES,
  SENSOR_ALIGNMENT_WRITE_FULL_BYTES,
  encodeAccTrim,
  ACC_TRIM_LIMIT,
  ACC_TRIM_WRITE_BYTES,
  encodeCompassConfig,
  COMPASS_CONFIG_WRITE_BYTES,
  MAG_DECLINATION_DECIDEGREE_LIMIT,
} from './msp';
export {
  decodePidTerms,
  decodeRcTuning,
  decodeFilterConfiguration,
  decodePidTuningSnapshot,
  PID_ITEM_COUNT,
  PID_AXIS_COUNT,
  PID_ADVANCED_API147_MIN_BYTES,
  RC_TUNING_API147_BYTES,
  FILTER_CONFIG_API147_BYTES,
  encodeChangedPidTuning,
} from './msp';
export type {
  MspPidTerm,
  MspRcTuning,
  MspFilterConfiguration,
  MspPidTuningSnapshot,
  PidTuningWriteGroup,
  EncodedPidTuningWrite,
} from './msp';
export {
  MSP_MODE_RANGES,
  MSP_SET_MODE_RANGE,
  MSP_BOXNAMES,
  MSP_MODE_RANGES_EXTRA,
  decodeModesConfiguration,
  encodeModeRangeWrites,
  MODE_RANGE_MIN,
  MODE_RANGE_MAX,
  MODE_RANGE_STEP,
  MODE_RANGE_SLOT_BYTES,
  MODE_RANGE_EXTRA_SLOT_BYTES,
} from './msp';
export type {
  MspModeDefinition,
  MspModeRangeSlot,
  MspModesConfiguration,
  EncodedModeRangeWrite,
} from './msp';
export {
  MSP_FAILSAFE_CONFIG,
  MSP_SET_FAILSAFE_CONFIG,
  MSP_RXFAIL_CONFIG,
  MSP_SET_RXFAIL_CONFIG,
  decodeFailsafeConfiguration,
  decodeRxFailsafeConfiguration,
  encodeChangedFailsafeConfiguration,
  RX_FAILSAFE_MIN,
  RX_FAILSAFE_MAX,
  RX_FAILSAFE_STEP,
  BUILD_OPTION_GPS,
  MSP_GPS_RESCUE,
  MSP_SET_GPS_RESCUE,
  decodeGpsRescue,
  encodeChangedGpsRescue,
  encodeGpsRescue,
  GPS_RESCUE_BASE_BYTES,
  GPS_RESCUE_WITH_RATES_BYTES,
  GPS_RESCUE_WITH_MIN_START_BYTES,
  GPS_RESCUE_FULL_BYTES,
  encodeSelectSetting,
  isEncodableProfileIndex,
  SELECT_SETTING_RATE_PROFILE_FLAG,
  SELECT_SETTING_MAX_INDEX,
} from './msp';
export type {
  FailsafeProcedure,
  FailsafeSwitchMode,
  RxFailsafeMode,
  MspFailsafeConfiguration,
  MspRxFailsafeChannel,
  MspFailsafeSnapshot,
  FailsafeWriteGroup,
  EncodedFailsafeWrite,
  GpsRescueAvailability,
  MspGpsRescueConfiguration,
  MspGpsRescuePreservedFields,
  SelectSettingProfileKind,
} from './msp';
export {MSP_BATTERY_CONFIG, MSP_SET_BATTERY_CONFIG, MSP_CURRENT_METER_CONFIG, MSP_SET_CURRENT_METER_CONFIG, MSP_VOLTAGE_METER_CONFIG, MSP_SET_VOLTAGE_METER_CONFIG, MSP_VOLTAGE_METERS, MSP_CURRENT_METERS, decodeBatteryConfiguration, decodeVoltageMeterConfiguration, decodeCurrentMeterConfiguration, encodeChangedPowerConfiguration} from './msp';
export type {MspBatteryConfiguration, MspVoltageMeterConfiguration, MspCurrentMeterConfiguration, MspPowerConfigurationSnapshot, PowerWriteGroup, EncodedPowerWrite} from './msp';
export {MSP_OSD_CONFIG, MSP_SET_OSD_CONFIG, MSP_OSD_CANVAS, decodeOsdConfiguration, decodeOsdCanvas, encodeChangedOsdConfiguration} from './msp';
export type {MspOsdConfiguration, MspOsdCanvas, MspOsdSnapshot, OsdWriteGroup, EncodedOsdWrite} from './msp';
export {MSP_SET_VTX_CONFIG, MSP_VTXTABLE_BAND, MSP_VTXTABLE_POWERLEVEL, MSP_SET_VTXTABLE_BAND, MSP_SET_VTXTABLE_POWERLEVEL, decodeVtxConfiguration, decodeVtxBand, decodeVtxPowerLevel, encodeChangedVtxConfiguration} from './msp';
export type {MspVtxConfiguration, MspVtxBand, MspVtxPowerLevel, MspVtxSnapshot, VtxWriteGroup, EncodedVtxWrite} from './msp';
export {MSP_RAW_IMU, MSP_ALTITUDE, decodeRawImu, decodeAltitude} from './msp';
export type {SensorVector3, MspRawImu, MspAltitude} from './msp';

export {
  decodeDetailedGps,
  decodeCompGps,
  decodeGpsConfiguration,
  decodeGpsSatelliteInfo,
  GPS_SATELLITE_MAX_COUNT,
  encodeGpsConfiguration,
} from './msp';
export type {
  MspDetailedGps,
  MspCompGps,
  MspGpsConfiguration,
  GpsConstellation,
  MspGpsSatellite,
  MspGpsSatelliteInfo,
} from './msp';
export {
  BETAFLIGHT_SOURCE_REPO,
  BETAFLIGHT_PINNED_COMMIT,
  BETAFLIGHT_API147_COMMIT,
  BETAFLIGHT_2025_12_2_COMMIT,
  INAV_SOURCE_REPO,
  INAV_PINNED_COMMIT,
  EMUFLIGHT_SOURCE_REPO,
  EMUFLIGHT_PINNED_COMMIT,
} from './msp';
export { MspPayloadReader, MspPayloadReadError } from './msp';
export {
  decodeApiVersion,
  decodeFcVariant,
  decodeBoardInfo,
  decodeAttitude,
  decodeBatteryState,
  decodeAnalog,
  decodeRawGps,
  decodeStatusEx,
} from './msp';
export {
  decodeStatusExReadiness,
  STATUS_EX_FIXED_PREFIX_BYTES,
  decodeStatusExDiagnostics,
} from './msp';
export type { MspStatusExReadiness, MspStatusExDiagnostics } from './msp';
export type {
  MspApiVersion,
  MspFcVariantRaw,
  MspBoardInfo,
  MspAttitude,
  MspBatteryState,
  MspAnalog,
  MspRawGpsCompact,
  MspStatusExCompact,
} from './msp';
export {
  decodeFeatureConfig,
  FEATURE_3D_BIT,
  decodeMixerConfig,
  MIXER_MODE_QUADX,
  MIXER_MODE_QUADX_1234,
  decodeAdvancedConfig,
  MOTOR_PROTOCOL_RAW_DSHOT600_AT_2025_12_2,
  decodeMotorConfig,
  decodeBlackboxConfig,
  BLACKBOX_CONFIG_PAYLOAD_BYTES,
  decodeDataflashSummary,
  DATAFLASH_FLAG_READY,
  DATAFLASH_FLAG_SUPPORTED,
  DATAFLASH_SUMMARY_PAYLOAD_BYTES,
  decodeSdcardSummary,
  SDCARD_FLAG_CONFIGURED,
  SDCARD_SUMMARY_PAYLOAD_BYTES,
  encodeBlackboxConfig,
  encodeAdvancedConfigDebugMode,
  ADVANCED_CONFIG_WRITE_BYTES,
  BLACKBOX_CONFIG_WRITE_BYTES,
  decodeMotor3dConfig,
  decodeMotorOutputs,
  MSP_MOTOR_OUTPUT_SLOT_COUNT,
  decodeMotorTelemetry,
  MSP_MOTOR_TELEMETRY_MAX_COUNT,
  decodeMotorOutputOrder,
  MOTOR_OUTPUT_ORDER_MAX_COUNT,
  encodeMotorOutputOrder,
  MotorOutputOrderEncodeError,
  encodeDshotEscDirection,
  DshotEscDirectionEncodeError,
  decodeSerialPorts,
  encodeSerialPorts,
  SERIAL_PORT_RECORD_MIN_BYTES,
  decodeBuildOptions,
  decodeSerialRxProvider,
  decodeVtxTableStatus,
  decodeArmingConfig,
  decodeBeeperConfig,
  decodeRxConfig,
  decodeRcChannels,
  decodeReceiverMap,
  decodeRssiConfig,
  decodeReceiverDeadband,
  decodeTxInfo,
  RECEIVER_CHANNEL_MAX_COUNT,
  decodeMspText,
  MSP_TEXT_PILOT_NAME,
  MSP_TEXT_CRAFT_NAME,
  MSP_TEXT_MAX_BYTES,
  encodeArmingConfiguration,
  encodeBeeperConfiguration,
  encodeAdvancedGeneralConfiguration,
  encodeRxCameraAngle,
  encodeMspTextRequest,
  encodeMspText,
  encodeChangedGeneralConfiguration,
  encodeReceiverMap,
  encodeReceiverDeadband,
  encodeReceiverConfig,
  encodeChangedReceiverConfiguration,
  encodeFeatureConfig,
} from './msp';
export type {
  MspFeatureConfig,
  MspMixerConfig,
  MspAdvancedConfig,
  MspMotorConfig,
  MspBlackboxConfig,
  MspDataflashSummary,
  MspSdcardSummary,
  BlackboxConfigWrite,
  MspMotor3dConfig,
  MspMotorOutputs,
  MspMotorTelemetry,
  MspMotorTelemetryEntry,
  MspMotorOutputOrder,
  DshotEscDirection,
  MspSerialPortRecord,
  MspBuildOptions,
  MspVtxTableStatus,
  MspArmingConfig,
  MspBeeperConfig,
  MspRxConfig,
  MspRcChannels,
  MspReceiverDeadband,
  MspTextValue,
  GeneralConfigurationWriteGroup,
  EncodedGeneralConfigurationWrite,
  ReceiverWriteGroup,
  EncodedReceiverWrite,
} from './msp';
export {
  checkMspCompatibility,
  MSP_MIN_REQUIRED_API_VERSION_MAJOR,
  MSP_MIN_REQUIRED_API_VERSION_MINOR,
} from './msp';
export type { MspCompatibilityResult } from './msp';
export type { ConnectionStage, ConnectionStageEvidence } from './msp';
export {
  boardIdentityNames,
  classifyConnectionStage,
  connectionStageLabelKey,
  boardMatchesTarget,
  describeFlightControllerHardware,
  deriveFcFamily,
  isIdentifiedFlightController,
  resolveCatalogTarget,
  MspIdentificationService,
  MspIncompatibleFirmwareError,
  BoxIdsAcquisition,
} from './msp';
export type { BoxIdsOwnerIdentity, BoxIdsResult } from './msp';
export type {
  MspFcFamily,
  MspFcVariant,
  FlightControllerIdentity,
  MspRequester,
} from './msp';

export { RealClock, FakeClock, createMspTelemetryScheduler } from './telemetry';
export type {
  MonotonicClock,
  MspPollDefinition,
  TelemetryValue,
  TelemetryPauseReason,
  TelemetryPauseLease,
  TelemetryPollDiagnostics,
  TelemetrySchedulerDiagnostics,
  MspTelemetryScheduler,
  MspTelemetrySchedulerOptions,
} from './telemetry';

export {
  MspOperationOutcomeUnknownError,
  createMspOperationCoordinator,
  MspExclusiveOperationInProgressError,
} from './telemetry';
export type {
  ExclusiveOperationState,
  OperationExecutionPhase,
  MspOperationContext,
  MspOperationValidationResult,
  MspExclusiveOperation,
  SetupOperationResult,
  MspOperationCoordinator,
  MspOperationSessionSource,
  MspOperationCoordinatorOptions,
} from './telemetry';

/* SENSORS - B-1 wire types. */
export type {
  SensorHardwareFamily,
  SensorHardwareKind,
  SensorHardwareValue,
  NotAvailableInThisContract,
  SensorConfig,
  SensorConfigContract,
  CustomAlignmentDecidegrees,
  SensorAlignment,
  SensorAlignmentKind,
  SensorAlignmentValue,
  DetectedSensor,
  SensorConfigActive,
  SensorNotAvailable,
  GyroSensorActive,
  AccTrim,
  CompassConfig,
  SensorConfigWrite,
  SensorAlignmentWrite,
  AccTrimWrite,
  CompassConfigWrite,
} from './msp';
