/**
 * M-D §4 - THE COMMANDABLE MOTOR COUNT HAS EXACTLY ONE SOURCE.
 *
 * The defect class this suite exists to prevent is not a crash. It is a
 * screen that renders four motor controls for a hexacopter because some
 * layer, somewhere, wrote `?? 4`. That produces a UI which looks correct,
 * commands two fewer motors than the aircraft has, and gives the operator
 * no signal at all that motors 5 and 6 were never tested.
 *
 * So the assertions below are mostly negative and mostly about NUMBERS
 * NOT APPEARING. Four in particular: on a tricopter, on a hexacopter, on
 * an unknown mixer and on an unread configuration, the answer 4 must never
 * be produced by anything in this module.
 *
 * Every fixture is hand-built from the pinned firmware's own values. None
 * of them is generated by the code under test.
 */

import {
  BETAFLIGHT_MIXER_REFERENCE_V147,
  MIXER_REFERENCE_MAX_SUPPORTED_MOTORS,
} from '../firmware-adapters/betaflightMixerReferenceV147';
import {
  commandableMotorScope,
  describeAirframe,
  describeExpectedMotorCount,
  describeRuntimeMotorCount,
  describeServoInvolvement,
  highestTopologyNoticeSeverity,
  topologyNotices,
  topologyPresentationMode,
} from './motorTopologyPresentation';
import {
  deriveMotorTopologyTruth,
  type MotorTopologyObservation,
} from './motorTopologyTruth';

/** Eight slots, the first `enabled` of them carrying a plausible external
 *  value. Hand-shaped to MSP_MOTOR's actual contract: always eight. */
function slots(enabled: number): readonly number[] {
  return Array.from({length: 8}, (_, index) => (index < enabled ? 1000 : 0));
}

function truth(observation: MotorTopologyObservation) {
  return deriveMotorTopologyTruth(observation);
}

/** mixerMode_e ordinals, from mixer.h:38-66 @ 7348054f. */
const TRI = 1;
const QUADX = 3;
const GIMBAL = 5;
const Y6 = 6;
const FLYING_WING = 8;
const HEX6X = 10;
const OCTOX8 = 11;
const AIRPLANE = 14;
const VTAIL4 = 17;
const CUSTOM = 23;
const CUSTOM_TRI = 25;
const QUADX_1234 = 26;

describe('M-D §4 - no fallback motor count exists anywhere', () => {
  it('reports NO count when MSP_MOTOR_CONFIG has not been read', () => {
    const scope = commandableMotorScope(truth({mixerModeRaw: QUADX}));
    expect(scope).toEqual({kind: 'RUNTIME_COUNT_NOT_READ'});
    // The failure this pins: a quad mixer is the ONE case where a lazy
    // `?? 4` would produce the right answer by accident, hiding the bug
    // until somebody connects a hexacopter.
    expect(JSON.stringify(scope)).not.toContain('4');
  });

  it('reports NO count for an unknown mixer with no runtime read', () => {
    const scope = commandableMotorScope(truth({mixerModeRaw: 250}));
    expect(scope).toEqual({kind: 'RUNTIME_COUNT_NOT_READ'});
  });

  it('never emits a count the controller would refuse', () => {
    // Above MAX_SUPPORTED_MOTORS: reported back as the figure it was,
    // never clamped down to eight and never replaced by four.
    const scope = commandableMotorScope(
      truth({mixerModeRaw: QUADX, runtimeMotorCount: 12}),
    );
    expect(scope).toEqual({kind: 'RUNTIME_COUNT_UNUSABLE', reported: 12});
    expect(MIXER_REFERENCE_MAX_SUPPORTED_MOTORS).toBe(8);
  });

  it('distinguishes "zero motors" from "not read"', () => {
    // Two different sentences. Only one of them means the operator should
    // wait for a read to finish.
    expect(
      commandableMotorScope(truth({mixerModeRaw: GIMBAL, runtimeMotorCount: 0})),
    ).toEqual({kind: 'NO_MOTORS_REPORTED'});
    expect(commandableMotorScope(truth({mixerModeRaw: GIMBAL}))).toEqual({
      kind: 'RUNTIME_COUNT_NOT_READ',
    });
  });

  it.each([
    ['TRI', TRI, 3],
    ['QUADX', QUADX, 4],
    ['Y6', Y6, 6],
    ['HEX6X', HEX6X, 6],
    ['OCTOX8', OCTOX8, 8],
    ['AIRPLANE', AIRPLANE, 1],
    ['FLYING_WING', FLYING_WING, 1],
    ['CUSTOM', CUSTOM, 5],
    ['UNKNOWN 250', 250, 3],
  ])(
    '%s: offers exactly the motor numbers the firmware reported',
    (_name, mixerModeRaw, runtimeMotorCount) => {
      const scope = commandableMotorScope(
        truth({mixerModeRaw, runtimeMotorCount}),
      );
      expect(scope).toEqual({
        kind: 'COMMANDABLE',
        count: runtimeMotorCount,
        motorNumbers: Array.from(
          {length: runtimeMotorCount},
          (_unused, index) => index + 1,
        ),
      });
    },
  );

  it('takes the count from MSP_MOTOR_CONFIG, never from the mixer table', () => {
    // A QUADX that boots reporting six. M-C established the runtime count
    // wins; this proves the presentation layer agrees.
    const scope = commandableMotorScope(
      truth({mixerModeRaw: QUADX, runtimeMotorCount: 6}),
    );
    expect(scope).toEqual({
      kind: 'COMMANDABLE',
      count: 6,
      motorNumbers: [1, 2, 3, 4, 5, 6],
    });
  });

  it('takes the count from MSP_MOTOR_CONFIG, never from the output frame', () => {
    // Every slot zero - the ordinary state while motorIsEnabled() is
    // clear, e.g. during ESC passthrough. Six motors remain six motors.
    const scope = commandableMotorScope(
      truth({
        mixerModeRaw: HEX6X,
        runtimeMotorCount: 6,
        motorOutputSlots: slots(0),
      }),
    );
    expect(scope).toEqual({
      kind: 'COMMANDABLE',
      count: 6,
      motorNumbers: [1, 2, 3, 4, 5, 6],
    });
  });

  it('takes the count from MSP_MOTOR_CONFIG, never from the telemetry frame', () => {
    const scope = commandableMotorScope(
      truth({
        mixerModeRaw: HEX6X,
        runtimeMotorCount: 6,
        telemetryFrameMotorCount: 4,
      }),
    );
    expect(scope).toEqual({
      kind: 'COMMANDABLE',
      count: 6,
      motorNumbers: [1, 2, 3, 4, 5, 6],
    });
  });
});

describe('M-D §7 / §11 - airframe identity is read, never normalised', () => {
  it('names every mixer in the pinned table by its own firmware name', () => {
    for (const entry of BETAFLIGHT_MIXER_REFERENCE_V147) {
      expect(describeAirframe(truth({mixerModeRaw: entry.mixerId}))).toEqual({
        key: `motorsScreen.topology.airframe.${entry.firmwareName}`,
      });
    }
  });

  it('keeps an unknown mixer raw instead of substituting a quad', () => {
    expect(describeAirframe(truth({mixerModeRaw: 250}))).toEqual({
      key: 'motorsScreen.topology.airframe.unknownRaw',
      params: {raw: 250},
    });
  });

  it('keeps QUADX and QUADX_1234 as different airframes', () => {
    // M-A established the two order their outputs differently. Same motor
    // count is not the same aircraft.
    const x = describeAirframe(truth({mixerModeRaw: QUADX}));
    const x1234 = describeAirframe(truth({mixerModeRaw: QUADX_1234}));
    expect(x).not.toEqual(x1234);
  });
});

describe('M-D §9 - expected and runtime are answered separately', () => {
  it('states both figures without merging them', () => {
    const state = truth({mixerModeRaw: QUADX, runtimeMotorCount: 6});
    expect(describeExpectedMotorCount(state)).toEqual({
      key: 'motorsScreen.topology.expectedCount.fixed',
      params: {count: 4},
    });
    expect(describeRuntimeMotorCount(commandableMotorScope(state))).toEqual({
      key: 'motorsScreen.topology.runtimeCount.reported',
      params: {count: 6},
    });
  });

  it('carries both figures on the mismatch notice, still apart', () => {
    const notices = topologyNotices(
      truth({mixerModeRaw: QUADX, runtimeMotorCount: 6}),
    );
    const mismatch = notices.find(
      notice => notice.id === 'RUNTIME_COUNT_DISAGREES_WITH_MIXER_TABLE',
    );
    expect(mismatch?.severity).toBe('DIAGNOSTIC');
    expect(mismatch?.comparison?.expected.params).toEqual({count: 4});
    expect(mismatch?.comparison?.reported.params).toEqual({count: 6});
  });

  it('does not let a mismatch revoke commandability', () => {
    // The whole point of M-C. A disagreement is reported; the six motors
    // stay commandable.
    const state = truth({mixerModeRaw: QUADX, runtimeMotorCount: 6});
    expect(topologyNotices(state).length).toBeGreaterThan(0);
    expect(commandableMotorScope(state)).toEqual({
      kind: 'COMMANDABLE',
      count: 6,
      motorNumbers: [1, 2, 3, 4, 5, 6],
    });
  });
});

describe('M-D §10 - a custom mixer is not a mismatch', () => {
  it.each([
    ['CUSTOM', CUSTOM],
    ['CUSTOM_TRI', CUSTOM_TRI],
  ])('%s raises no expected-count mismatch', (_name, mixerModeRaw) => {
    const state = truth({mixerModeRaw, runtimeMotorCount: 5});
    expect(
      topologyNotices(state).map(notice => notice.id),
    ).not.toContain('RUNTIME_COUNT_DISAGREES_WITH_MIXER_TABLE');
  });

  it('explains the absent expectation instead of calling it unknown', () => {
    const state = truth({mixerModeRaw: CUSTOM, runtimeMotorCount: 5});
    expect(describeExpectedMotorCount(state)).toEqual({
      key: 'motorsScreen.topology.expectedCount.customRuntimeDerived',
    });
    const notices = topologyNotices(state);
    expect(notices.map(notice => notice.id)).toContain(
      'CUSTOM_TOPOLOGY_NOT_OBSERVABLE_OVER_MSP',
    );
    expect(highestTopologyNoticeSeverity(notices)).toBe('INFORMATIONAL');
  });
});

describe('M-D §22 / §55 - a diagram needs an authored layout', () => {
  it.each([
    ['QUADX', QUADX, 4],
    ['QUADX_1234', QUADX_1234, 4],
  ])('%s draws its authored layout', (_name, mixerModeRaw, count) => {
    expect(
      topologyPresentationMode(truth({mixerModeRaw, runtimeMotorCount: count})),
    ).toBe('POSITIONAL_DIAGRAM');
  });

  it.each([
    ['TRI', TRI, 3],
    ['Y6', Y6, 6],
    ['HEX6X', HEX6X, 6],
    ['OCTOX8', OCTOX8, 8],
    ['VTAIL4', VTAIL4, 4],
    ['FLYING_WING', FLYING_WING, 1],
    ['AIRPLANE', AIRPLANE, 1],
    ['CUSTOM', CUSTOM, 5],
    ['UNKNOWN 250', 250, 3],
  ])('%s falls back to a numbered list', (_name, mixerModeRaw, count) => {
    // VTAIL4 is the case worth naming: four motors, and NOT an X. Motor
    // count alone never licenses a drawing.
    expect(
      topologyPresentationMode(truth({mixerModeRaw, runtimeMotorCount: count})),
    ).toBe('NUMBERED_LIST');
  });

  it('withdraws the diagram when the machine stopped matching it', () => {
    // A quad layout describes four motors. Six reported means the drawing
    // is now a lie, whatever the mixer byte says.
    expect(
      topologyPresentationMode(truth({mixerModeRaw: QUADX, runtimeMotorCount: 6})),
    ).toBe('NUMBERED_LIST');
  });

  it('draws nothing before the count is known', () => {
    expect(topologyPresentationMode(truth({mixerModeRaw: QUADX}))).toBe(
      'NUMBERED_LIST',
    );
  });
});

describe('M-D §12 / §50 - servos are named, never offered', () => {
  it('names the tricopter tail servo', () => {
    const involvement = describeServoInvolvement(
      truth({mixerModeRaw: TRI, runtimeMotorCount: 3}),
    );
    expect(involvement).toEqual({
      kind: 'SERVO_OUTPUTS',
      count: 1,
      phrase: {key: 'motorsScreen.topology.servo.TRI', params: {count: 1}},
    });
  });

  it.each([
    ['FLYING_WING', FLYING_WING, 2],
    ['AIRPLANE', AIRPLANE, 6],
  ])('%s names its control surfaces', (_name, mixerModeRaw, count) => {
    const involvement = describeServoInvolvement(
      truth({mixerModeRaw, runtimeMotorCount: 1}),
    );
    expect(involvement.kind).toBe('SERVO_OUTPUTS');
    expect(involvement.kind === 'SERVO_OUTPUTS' && involvement.count).toBe(count);
  });

  it('says nothing about servos on a mixer that has none', () => {
    expect(
      describeServoInvolvement(truth({mixerModeRaw: HEX6X, runtimeMotorCount: 6})),
    ).toEqual({kind: 'NO_SERVOS'});
  });

  it('claims no servo count for an unknown mixer', () => {
    expect(describeServoInvolvement(truth({mixerModeRaw: 250}))).toEqual({
      kind: 'UNKNOWN',
    });
  });

  it('never adds a servo to the commandable motor list', () => {
    // The tricopter's fourth output is a servo. It must not become a
    // fourth motor control, which is precisely what a naive
    // "outputs = motors + servos" would produce.
    const scope = commandableMotorScope(
      truth({mixerModeRaw: TRI, runtimeMotorCount: 3}),
    );
    expect(scope).toEqual({
      kind: 'COMMANDABLE',
      count: 3,
      motorNumbers: [1, 2, 3],
    });
  });
});

describe('M-D §52 - severity matches meaning', () => {
  it('treats an unknown mixer as information, not a fault', () => {
    const notices = topologyNotices(truth({mixerModeRaw: 250, runtimeMotorCount: 3}));
    expect(notices).toHaveLength(1);
    expect(notices[0]).toEqual({
      id: 'MIXER_MODE_NOT_IN_PINNED_TABLE',
      severity: 'INFORMATIONAL',
      phrase: {
        key: 'motorsScreen.topology.notice.MIXER_MODE_NOT_IN_PINNED_TABLE',
        params: {raw: 250},
      },
    });
  });

  it('treats a telemetry-count disagreement as diagnostic', () => {
    const notices = topologyNotices(
      truth({
        mixerModeRaw: HEX6X,
        runtimeMotorCount: 6,
        telemetryFrameMotorCount: 4,
      }),
    );
    const telemetry = notices.find(
      notice => notice.id === 'TELEMETRY_FRAME_COUNT_DISAGREES_WITH_RUNTIME_COUNT',
    );
    expect(telemetry?.severity).toBe('DIAGNOSTIC');
    expect(telemetry?.phrase.params).toEqual({telemetry: 4, runtime: 6});
  });

  it('treats a firmware-impossible reading as a contradiction', () => {
    const notices = topologyNotices(
      truth({mixerModeRaw: QUADX, runtimeMotorCount: 12}),
    );
    expect(
      notices.find(n => n.id === 'RUNTIME_COUNT_EXCEEDS_FIRMWARE_MAXIMUM')?.severity,
    ).toBe('CONTRADICTION');
    expect(highestTopologyNoticeSeverity(notices)).toBe('CONTRADICTION');
  });

  it('says nothing at all when the board is self-consistent', () => {
    const notices = topologyNotices(
      truth({
        mixerModeRaw: HEX6X,
        runtimeMotorCount: 6,
        motorOutputSlots: slots(6),
        telemetryFrameMotorCount: 6,
      }),
    );
    expect(notices).toEqual([]);
    // Undefined, not a fourth "all clear" level: a screen must be able to
    // render nothing rather than a cleared alarm.
    expect(highestTopologyNoticeSeverity(notices)).toBeUndefined();
  });

  it('reports a zero-motor servo mixer without calling it an error', () => {
    const state = truth({mixerModeRaw: GIMBAL, runtimeMotorCount: 0});
    expect(topologyNotices(state)).toEqual([]);
    expect(commandableMotorScope(state)).toEqual({kind: 'NO_MOTORS_REPORTED'});
  });
});

describe('M-D §25 / §53 - the vocabulary this module may not use', () => {
  /** Every phrase this module can produce, across every mixer in the
   *  pinned table and every count from 0 to 9. Collected by walking the
   *  real functions rather than by reading the source, so a key added
   *  later is covered without anyone remembering to add it here. */
  function everyKey(): readonly string[] {
    const keys: string[] = [];
    const ids = [
      ...BETAFLIGHT_MIXER_REFERENCE_V147.map(entry => entry.mixerId),
      250,
    ];
    for (const mixerModeRaw of ids) {
      for (const runtimeMotorCount of [undefined, 0, 1, 3, 4, 5, 6, 8, 9, 12]) {
        for (const telemetryFrameMotorCount of [undefined, 4]) {
          const state = truth({
            mixerModeRaw,
            runtimeMotorCount,
            telemetryFrameMotorCount,
          });
          const scope = commandableMotorScope(state);
          keys.push(describeAirframe(state).key);
          keys.push(describeRuntimeMotorCount(scope).key);
          keys.push(describeExpectedMotorCount(state).key);
          const servo = describeServoInvolvement(state);
          if (servo.kind === 'SERVO_OUTPUTS') {
            keys.push(servo.phrase.key);
          }
          for (const notice of topologyNotices(state)) {
            keys.push(notice.phrase.key);
            if (notice.comparison !== undefined) {
              keys.push(notice.comparison.expected.key);
              keys.push(notice.comparison.reported.key);
            }
          }
        }
      }
    }
    return keys;
  }

  it('produces a large, non-trivial key set (the sweep is not vacuous)', () => {
    expect(new Set(everyKey()).size).toBeGreaterThan(40);
  });

  it('contains no health vocabulary', () => {
    // Topology is a configuration. Nothing here measures whether a motor
    // works, so nothing here may imply it does.
    const forbidden =
      /healthy|unhealthy|\bok\b|working|good|bad|fault|broken|failure|sound/i;
    for (const key of new Set(everyKey())) {
      expect(key).not.toMatch(forbidden);
    }
  });

  it('contains no rotation-direction vocabulary', () => {
    // M-A: actual propeller rotation is not readable as authoritative
    // truth over MSP, so this module has no word for it.
    const forbidden = /\bcw\b|\bccw\b|clockwise|counterclockwise|reversed|spin/i;
    for (const key of new Set(everyKey())) {
      expect(key).not.toMatch(forbidden);
    }
  });

  it('exposes no rotation-direction field on any value it returns', () => {
    const state = truth({
      mixerModeRaw: QUADX,
      runtimeMotorCount: 4,
      motorOutputSlots: slots(4),
    });
    const serialised = JSON.stringify({
      airframe: describeAirframe(state),
      scope: commandableMotorScope(state),
      servo: describeServoInvolvement(state),
      notices: topologyNotices(state),
      mode: topologyPresentationMode(state),
    });
    expect(serialised).not.toMatch(/direction|rotation|clockwise|propeller/i);
  });
});
