export type {
  Transport,
  TransportDataListener,
  TransportDisconnectListener,
  TransportErrorListener,
  TransportUnsubscribe,
} from './transport';

export * from './firmware-flasher';

export type {
  MspWireFormat,
  MspProtocolVersion,
  MspDirection,
  MspFrame,
  MspDiagnostic,
  MspDiagnosticCode,
  MspDiagnosticDetailMap,
  MspDiagnosticDetail,
  MspEncodeOptions,
  MspStreamParser,
  MspStreamParserOptions,
  MspIngestEvent,
  MspIngestResult,
  MspTransport,
  MspTransportError,
  MspTransportSessionDetachedEvent,
  MspTransportUnsubscribe,
  MspClientErrorCode,
  MspClientState,
  MspRequestPhase,
  MspRequestOptions,
  MspClientOptions,
  MspClientDiagnosticEvent,
  MspApiVersion,
  MspFcVariantRaw,
  MspBoardInfo,
  MspAttitude,
  MspBatteryState,
  MspAnalog,
  MspRawGpsCompact,
  MspStatusExCompact,
  MspStatusExReadiness,
  MspStatusExDiagnostics,
  MspFeatureConfig,
  MspMixerConfig,
  MspAdvancedConfig,
  MspMotorConfig,
  MspMotor3dConfig,
  MspMotorOutputs,
  MspMotorTelemetry,
  MspMotorTelemetryEntry,
  MspMotorOutputOrder,
  DshotEscDirection,
  MspSerialPortRecord,
  MspBuildOptions,
  MspVtxTableStatus,
  MspArmingConfig,
  MspBeeperConfig,
  MspRxConfig,
  MspTextValue,
  MspPidTerm,
  MspRcTuning,
  MspFilterConfiguration,
  MspPidTuningSnapshot,
  PidTuningWriteGroup,
  EncodedPidTuningWrite,
  GeneralConfigurationWriteGroup,
  EncodedGeneralConfigurationWrite,
  ConnectionStage,
  ConnectionStageEvidence,
  MspCompatibilityResult,
  MspFcFamily,
  MspFcVariant,
  FlightControllerIdentity,
  MspRequester,
  MonotonicClock,
  MspPollDefinition,
  TelemetryValue,
  TelemetryPauseReason,
  TelemetryPauseLease,
  TelemetryPollDiagnostics,
  TelemetrySchedulerDiagnostics,
  MspTelemetryScheduler,
  MspTelemetrySchedulerOptions,
  ExclusiveOperationState,
  OperationExecutionPhase,
  MspOperationContext,
  MspOperationValidationResult,
  MspExclusiveOperation,
  SetupOperationResult,
  MspOperationCoordinator,
  MspOperationSessionSource,
  MspOperationCoordinatorOptions,
} from './protocol';
export {
  MSP_V2_FRAME_ID,
  MSP_MAX_PAYLOAD_BYTES_DEFAULT,
  MSP_PROTOCOL_SIZE_FIELD_CEILING,
  MSP_PARTIAL_FRAME_TIMEOUT_MS_DEFAULT,
  MSP_DIAGNOSTIC_CODES,
  xorChecksumStep,
  xorChecksum,
  crc8DvbS2Step,
  crc8DvbS2,
  encode,
  createMspStreamParser,
  MSP_CLIENT_ERROR_CODES,
  MspClient,
  MspClientError,
  MSP_CLIENT_MAX_PENDING_REQUESTS_DEFAULT,
  MSP_RESPONSE_TIMEOUT_MILLIS,
  MSP_API_VERSION,
  MSP_FC_VARIANT,
  MSP_BUILD_INFO,
  MSP_BOARD_INFO,
  MSP_ATTITUDE,
  MSP_BATTERY_STATE,
  MSP_RAW_GPS,
  MSP_COMP_GPS,
  MSP_GPS_CONFIG,
  MSP_GPS_SV_INFO,
  MSP_ANALOG,
  MSP_STATUS_EX,
  MSP_TX_INFO,
  MSP_BOXIDS,
  MSP_ACC_CALIBRATION,
  MSP_MAG_CALIBRATION,
  MSP_REBOOT,
  MSP_NAME,
  MSP_SET_NAME,
  STATUS_SENSOR_GPS_BIT,
  MSP_FEATURE_CONFIG,
  MSP_SET_FEATURE_CONFIG,
  MSP_SET_RX_CONFIG,
  MSP_RSSI_CONFIG,
  MSP_SET_RSSI_CONFIG,
  MSP_RX_MAP,
  MSP_SET_RX_MAP,
  MSP_ARMING_CONFIG,
  MSP_SET_ARMING_CONFIG,
  MSP_BEEPER_CONFIG,
  MSP_SET_BEEPER_CONFIG,
  MSP2_GET_TEXT,
  MSP2_SET_TEXT,
  MSP_MIXER_CONFIG,
  MSP_ADVANCED_CONFIG,
  MSP_MOTOR,
  MSP_RC,
  MSP_RC_TUNING,
  MSP_PID,
  MSP_FILTER_CONFIG,
  MSP_PID_ADVANCED,
  MSP_SET_FILTER_CONFIG,
  MSP_SET_PID_ADVANCED,
  MSP_SET_PID,
  MSP_SET_RC_TUNING,
  MSP_MOTOR_3D_CONFIG,
  MSP_RC_DEADBAND,
  MSP_MOTOR_CONFIG,
  MSP_MOTOR_TELEMETRY,
  MSP2_MOTOR_OUTPUT_REORDERING,
  MSP2_SET_MOTOR_OUTPUT_REORDERING,
  MSP2_SEND_DSHOT_COMMAND,
  MSP_SET_MIXER_CONFIG,
  MSP_SET_ADVANCED_CONFIG,
  MSP_SET_MOTOR_3D_CONFIG,
  MSP_SET_RC_DEADBAND,
  MSP_SET_MOTOR_CONFIG,
  MSP_SET_GPS_CONFIG,
  MSP_EEPROM_WRITE,
  MSP_RX_CONFIG,
  MSP_VTX_CONFIG,
  MSP2_COMMON_SERIAL_CONFIG,
  MSP2_COMMON_SET_SERIAL_CONFIG,
  BETAFLIGHT_SOURCE_REPO,
  BETAFLIGHT_PINNED_COMMIT,
  BETAFLIGHT_API147_COMMIT,
  BETAFLIGHT_2025_12_2_COMMIT,
  INAV_SOURCE_REPO,
  INAV_PINNED_COMMIT,
  EMUFLIGHT_SOURCE_REPO,
  EMUFLIGHT_PINNED_COMMIT,
  MspPayloadReader,
  MspPayloadReadError,
  decodeApiVersion,
  decodeFcVariant,
  decodeBoardInfo,
  decodeAttitude,
  decodeBatteryState,
  decodeAnalog,
  decodeRawGps,
  decodeDetailedGps,
  decodeCompGps,
  decodeGpsConfiguration,
  decodeGpsSatelliteInfo,
  GPS_SATELLITE_MAX_COUNT,
  encodeGpsConfiguration,
  decodeStatusEx,
  decodeStatusExReadiness,
  decodeStatusExDiagnostics,
  STATUS_EX_FIXED_PREFIX_BYTES,
  decodeFeatureConfig,
  FEATURE_3D_BIT,
  decodeMixerConfig,
  MIXER_MODE_QUADX,
  MIXER_MODE_QUADX_1234,
  decodeAdvancedConfig,
  MOTOR_PROTOCOL_RAW_DSHOT600_AT_2025_12_2,
  decodeMotorConfig,
  decodeMotor3dConfig,
  decodeMotorOutputs,
  MSP_MOTOR_OUTPUT_SLOT_COUNT,
  decodeMotorTelemetry,
  MSP_MOTOR_TELEMETRY_MAX_COUNT,
  decodeMotorOutputOrder,
  MOTOR_OUTPUT_ORDER_MAX_COUNT,
  encodeMotorOutputOrder,
  MotorOutputOrderEncodeError,
  encodeDshotEscDirection,
  DshotEscDirectionEncodeError,
  decodeSerialPorts,
  encodeSerialPorts,
  SERIAL_PORT_RECORD_MIN_BYTES,
  decodeBuildOptions,
  decodeSerialRxProvider,
  decodeVtxTableStatus,
  decodeArmingConfig,
  decodeBeeperConfig,
  decodeRxConfig,
  decodeRcChannels,
  decodeReceiverMap,
  decodeRssiConfig,
  decodeReceiverDeadband,
  decodeTxInfo,
  RECEIVER_CHANNEL_MAX_COUNT,
  decodePidTerms,
  decodeRcTuning,
  decodeFilterConfiguration,
  decodePidTuningSnapshot,
  PID_ITEM_COUNT,
  PID_AXIS_COUNT,
  PID_ADVANCED_API147_MIN_BYTES,
  RC_TUNING_API147_BYTES,
  FILTER_CONFIG_API147_BYTES,
  encodeChangedPidTuning,
  decodeMspText,
  MSP_TEXT_PILOT_NAME,
  MSP_TEXT_CRAFT_NAME,
  MSP_TEXT_MAX_BYTES,
  encodeArmingConfiguration,
  encodeBeeperConfiguration,
  encodeAdvancedGeneralConfiguration,
  encodeRxCameraAngle,
  encodeMspTextRequest,
  encodeMspText,
  encodeChangedGeneralConfiguration,
  encodeReceiverMap,
  encodeReceiverDeadband,
  encodeReceiverConfig,
  encodeChangedReceiverConfiguration,
  encodeFeatureConfig,
  checkMspCompatibility,
  MSP_MIN_REQUIRED_API_VERSION_MAJOR,
  MSP_MIN_REQUIRED_API_VERSION_MINOR,
  boardIdentityNames,
  classifyConnectionStage,
  connectionStageLabelKey,
  boardMatchesTarget,
  describeFlightControllerHardware,
  deriveFcFamily,
  isIdentifiedFlightController,
  resolveCatalogTarget,
  MspIdentificationService,
  MspIncompatibleFirmwareError,
  BoxIdsAcquisition,
  RealClock,
  FakeClock,
  createMspTelemetryScheduler,
  MspOperationOutcomeUnknownError,
  createMspOperationCoordinator,
  MspExclusiveOperationInProgressError,
} from './protocol';

export {
  createPidTuningDraft,
  ratesEqual,
  filtersEqual,
  pidTuningDraftsEqual,
  pidTuningSnapshotsEqual,
  validatePidTuningDraft,
} from './state/pidTuningModel';
export type {
  PidAxisKey,
  PidAxisDraft,
  RateAxisDraft,
  RatesDraft,
  FiltersDraft,
  PidTuningDraft,
  PidTuningValidationCode,
} from './state/pidTuningModel';
export {
  MODES_AUX_CHANNEL_COUNT,
  createModesConfigurationDraft,
  modesDraftsEqual,
  modesSnapshotsEqual,
  validateModesDraft,
  conditionsForMode,
  modeIsActive,
  modeArabicName,
} from './state/modesConfigurationModel';
export type {
  ModeConditionDraft,
  ModesConfigurationDraft,
  ModesValidationCode,
} from './state/modesConfigurationModel';
export {
  MSP_MODE_RANGES,
  MSP_SET_MODE_RANGE,
  MSP_BOXNAMES,
  MSP_MODE_RANGES_EXTRA,
  decodeModesConfiguration,
  encodeModeRangeWrites,
  MODE_RANGE_MIN,
  MODE_RANGE_MAX,
  MODE_RANGE_STEP,
  MODE_RANGE_SLOT_BYTES,
  MODE_RANGE_EXTRA_SLOT_BYTES,
} from './protocol';
export type {
  MspModeDefinition,
  MspModeRangeSlot,
  MspModesConfiguration,
  EncodedModeRangeWrite,
} from './protocol';
export {
  MSP_FAILSAFE_CONFIG,
  MSP_SET_FAILSAFE_CONFIG,
  MSP_RXFAIL_CONFIG,
  MSP_SET_RXFAIL_CONFIG,
  decodeFailsafeConfiguration,
  decodeRxFailsafeConfiguration,
  encodeChangedFailsafeConfiguration,
  RX_FAILSAFE_MIN,
  RX_FAILSAFE_MAX,
  RX_FAILSAFE_STEP,
  BUILD_OPTION_GPS,
  MSP_GPS_RESCUE,
  MSP_SET_GPS_RESCUE,
  decodeGpsRescue,
  encodeChangedGpsRescue,
  encodeGpsRescue,
  GPS_RESCUE_BASE_BYTES,
  GPS_RESCUE_WITH_RATES_BYTES,
  GPS_RESCUE_WITH_MIN_START_BYTES,
  GPS_RESCUE_FULL_BYTES,
  encodeSelectSetting,
  isEncodableProfileIndex,
  SELECT_SETTING_RATE_PROFILE_FLAG,
  SELECT_SETTING_MAX_INDEX,
} from './protocol';
export type {
  FailsafeProcedure,
  FailsafeSwitchMode,
  RxFailsafeMode,
  MspFailsafeConfiguration,
  MspRxFailsafeChannel,
  MspFailsafeSnapshot,
  FailsafeWriteGroup,
  EncodedFailsafeWrite,
  GpsRescueAvailability,
  MspGpsRescueConfiguration,
  MspGpsRescuePreservedFields,
  SelectSettingProfileKind,
} from './protocol';
export {
  createFailsafeConfigurationDraft,
  failsafeDraftsEqual,
  failsafeSnapshotsEqual,
  validateFailsafeDraft,
} from './state/failsafeConfigurationModel';
export type {
  FailsafeChannelDraft,
  FailsafeConfigurationDraft,
  FailsafeValidationCode,
} from './state/failsafeConfigurationModel';
export {
  createGpsRescueDraft,
  gpsRescueDraftsEqual,
  gpsRescueSnapshotsEqual,
  validateGpsRescueDraft,
  gpsRescueSupportsRates,
  gpsRescueSupportsMinStartDistance,
  gpsRescueSupportsInitialClimb,
  GPS_RESCUE_RANGES,
} from './state/gpsRescueConfigurationModel';
export type {
  GpsRescueDraft,
  GpsRescueRange,
  GpsRescueSanityCheck,
  GpsRescueAltitudeMode,
  GpsRescueValidationCode,
} from './state/gpsRescueConfigurationModel';
export {
  MSP_BATTERY_CONFIG,
  MSP_SET_BATTERY_CONFIG,
  MSP_CURRENT_METER_CONFIG,
  MSP_SET_CURRENT_METER_CONFIG,
  MSP_VOLTAGE_METER_CONFIG,
  MSP_SET_VOLTAGE_METER_CONFIG,
  MSP_VOLTAGE_METERS,
  MSP_CURRENT_METERS,
  decodeBatteryConfiguration,
  decodeVoltageMeterConfiguration,
  decodeCurrentMeterConfiguration,
  encodeChangedPowerConfiguration,
} from './protocol';
export type {
  MspBatteryConfiguration,
  MspVoltageMeterConfiguration,
  MspCurrentMeterConfiguration,
  MspPowerConfigurationSnapshot,
  PowerWriteGroup,
  EncodedPowerWrite,
} from './protocol';
export {
  createPowerConfigurationDraft,
  powerDraftsEqual,
  powerSnapshotsEqual,
  validatePowerDraft,
} from './state/powerConfigurationModel';
export type {
  PowerConfigurationDraft,
  PowerValidationCode,
} from './state/powerConfigurationModel';
export {
  MSP_OSD_CONFIG,
  MSP_SET_OSD_CONFIG,
  MSP_OSD_CANVAS,
  decodeOsdConfiguration,
  decodeOsdCanvas,
  encodeChangedOsdConfiguration,
} from './protocol';
export type {
  MspOsdConfiguration,
  MspOsdCanvas,
  MspOsdSnapshot,
  OsdWriteGroup,
  EncodedOsdWrite,
} from './protocol';
export {
  OSD_PROFILE_BITS_POSITION,
  OSD_PROFILE_MASK,
  OSD_TYPE_MASK,
  OSD_POSITION_MASK,
  createOsdConfigurationDraft,
  osdDraftsEqual,
  osdSnapshotsEqual,
  osdPositionX,
  osdPositionY,
  osdElementType,
  osdVisibleInProfile,
  setOsdPosition,
  setOsdProfileVisibility,
  validateOsdDraft,
  OSD_ELEMENT_NAMES_AR,
  osdElementName,
  OSD_ELEMENT_TOKENS,
  osdElementToken,
} from './state/osdConfigurationModel';
export type {
  OsdConfigurationDraft,
  OsdValidationCode,
} from './state/osdConfigurationModel';
export {
  OSD_VIDEO_AUTO,
  OSD_VIDEO_PAL,
  OSD_VIDEO_NTSC,
  OSD_VIDEO_HD,
  OSD_PAL_GRID,
  OSD_NTSC_GRID,
  OSD_CELL_WIDTH_UNITS,
  OSD_CELL_HEIGHT_UNITS,
  resolveOsdCanvas,
  osdPreviewAspectRatio,
  osdCellSize,
  clampOsdCell,
  isCellWithinCanvas,
  pointToOsdCell,
  osdCellToPoint,
  osdCellToFraction,
  beginOsdDrag,
  resolveOsdDragCell,
  hitTestOsdElements,
} from './state/osdLayoutGeometry';
export type {
  OsdCell,
  OsdPoint,
  OsdPreviewBox,
  OsdDragGrab,
  OsdHitTarget,
} from './state/osdLayoutGeometry';
export {
  MSP_SET_VTX_CONFIG,
  MSP_VTXTABLE_BAND,
  MSP_VTXTABLE_POWERLEVEL,
  MSP_SET_VTXTABLE_BAND,
  MSP_SET_VTXTABLE_POWERLEVEL,
  decodeVtxConfiguration,
  decodeVtxBand,
  decodeVtxPowerLevel,
  encodeChangedVtxConfiguration,
} from './protocol';
export type {
  MspVtxConfiguration,
  MspVtxBand,
  MspVtxPowerLevel,
  MspVtxSnapshot,
  VtxWriteGroup,
  EncodedVtxWrite,
} from './protocol';
export {
  createVtxConfigurationDraft,
  vtxDraftsEqual,
  vtxSnapshotsEqual,
  validateVtxDraft,
  vtxDeviceName,
} from './state/vtxConfigurationModel';
export type {
  VtxConfigurationDraft,
  VtxValidationCode,
} from './state/vtxConfigurationModel';
export {
  MSP_RAW_IMU,
  MSP_ALTITUDE,
  decodeRawImu,
  decodeAltitude,
} from './protocol';
export type { SensorVector3, MspRawImu, MspAltitude } from './protocol';
export type {
  MspDetailedGps,
  MspCompGps,
  MspGpsConfiguration,
  GpsConstellation,
  MspGpsSatellite,
  MspGpsSatelliteInfo,
} from './protocol';
export type {
  MspRcChannels,
  MspReceiverDeadband,
  ReceiverWriteGroup,
  EncodedReceiverWrite,
} from './protocol';
export {
  SERIAL_BAUD_RATES,
  SERIAL_ROLE_DEFINITIONS,
  SERIAL_KNOWN_FUNCTION_MASK,
  serialPortDisplayName,
  serialRoleIsAvailable,
  hasSerialRole,
  enabledSerialRoles,
  unknownSerialFunctionMask,
  setSerialRole,
  setSerialBaud,
  availableBaudIndexes,
  validateSerialPorts,
  normalizeSerialPortsForSave,
  deriveSerialPortsFeatureMask,
  FEATURE_RX_SERIAL_BIT,
  FEATURE_GPS_BIT,
  FEATURE_TELEMETRY_BIT,
  FEATURE_ESC_SENSOR_BIT_FOR_PORTS,
  serialPortsEqual,
} from './state';
export type {
  SerialRoleCategory,
  SerialRoleKey,
  SerialRoleDefinition,
  SerialPortsSnapshot,
  SerialPortsValidationCode,
  SerialPortsValidationIssue,
  SerialBaudField,
} from './state';
export {
  GPS_FEATURE_BIT,
  GPS_PROVIDERS,
  GPS_SBAS_MODES,
  createGpsConfigurationDraft,
  hasGpsFeature,
  deriveGpsFeatureMask,
  gpsDraftsEqual,
  gpsConfigurationsEqual,
  validateGpsDraft,
  assignedGpsPorts,
} from './state';
export type {
  GpsConfigurationSnapshot,
  GpsConfigurationDraft,
  GpsConfigurationValidationCode,
} from './state';
export {
  GENERAL_FEATURES,
  BEEPER_CONDITIONS,
  DSHOT_BEACON_CONDITIONS,
  GENERAL_FEATURE_EDITABLE_MASK,
  BEEPER_EDITABLE_MASK,
  DSHOT_BEACON_EDITABLE_MASK,
  createGeneralConfigurationDraft,
  bitEnabled,
  setMaskBit,
  featureIsAvailable,
  generalConfigurationDraftsEqual,
  generalConfigurationSnapshotsEqual,
  generalConfigurationChangedCount,
  validateGeneralConfigurationDraft,
} from './state';
export type {
  GeneralFeatureDefinition,
  BeeperConditionDefinition,
  GeneralConfigurationSnapshot,
  GeneralConfigurationDraft,
  GeneralConfigurationValidationCode,
} from './state';
export {
  RECEIVER_MAP_LETTERS,
  receiverMapToText,
  receiverMapFromText,
  createReceiverConfigurationDraft,
  receiverDraftsEqual,
  receiverSnapshotsEqual,
  validateReceiverDraft,
  RECEIVER_REBOOT_SENSITIVE_FIELDS,
  receiverChangeMayRequireReboot,
  resolveReceiverMode,
  resolveReceiverPortDependency,
  resolveReceiverSignalState,
  resolveRssiSource,
  receiverProviderIsMeaningful,
  receiverValuesMayBeFailsafeOutput,
  RECEIVER_MODE_FEATURE_MASK,
  RECEIVER_FAILSAFE_BIT,
  RECEIVER_RXLOSS_BIT,
  RECEIVER_BOXFAILSAFE_BIT,
  RSSI_SOURCE_TOKENS,
  RECEIVER_MODE_CAPABILITY,
  WRITABLE_RECEIVER_MODES,
  RECEIVER_MODE_APPLY_REQUIREMENT,
  RECEIVER_PROVIDER_APPLY_REQUIREMENT,
  receiverModeIsWritable,
  receiverOwnedModeBits,
  applyReceiverModeToFeatureMask,
  receiverModeBaseIsStale,
  resolveReceiverTargetDependency,
  receiverModeAfterMutation,
  receiverModeIsSelectable,
  selectableReceiverModes,
  providerWriteIsPermitted,
  resolveProviderAvailability,
  resolveModeAvailability,
  selectableProviders,
  RECEIVER_MODE_BUILD_OPTION,
  BUILD_OPTION_RX_PPM,
  BUILD_OPTION_SERIALRX_CRSF,
  SERIAL_RX_PROVIDER_MAX,
} from './state';
export type {
  ReceiverBuildAvailability,
  ReceiverModeCapability,
  ReceiverModeWriteClassification,
  ReceiverApplyRequirement,
  ReceiverDependencyVerdict,
  ReceiverMode,
  ReceiverPortDependency,
  ReceiverSignalState,
  ReceiverRssiSource,
} from './state';
export type {
  ReceiverConfigurationSnapshot,
  ReceiverConfigurationDraft,
  ReceiverConfigurationValidationCode,
} from './state';
export {
  deriveOrientationViewState,
  describeOrientationForAccessibility,
} from './state';
export type { OrientationViewOffset, OrientationViewState } from './state';
export { deriveMotorOutputOrder } from './state/motorOutputReordering';
export type { MotorOutputReorderDerivation } from './state/motorOutputReordering';
export {
  evaluateMotorIdentificationCapability,
  MOTOR_IDENTIFICATION_MODEL_OUTPUT_COUNT,
} from './state/motorIdentificationCapability';
export type { MotorIdentificationCapability } from './state/motorIdentificationCapability';
export {
  analyzeOrientationStability,
  ORIENTATION_STABILITY_WINDOW_MS,
  ORIENTATION_STABILITY_MIN_SAMPLES,
  ORIENTATION_STABILITY_LIMITS,
} from './state';
export type {
  OrientationStabilitySample,
  OrientationStabilityResult,
} from './state';
export {
  rankArmingBlockReasons,
  selectTopArmingBlockReasons,
} from './state';
export type {
  ArmingBlockSeverity,
  ArmingBlockReason,
  ArmingReadiness,
  ArmingReadinessUnknownCause,
  ArmingBlockReasonSelection,
} from './state';
export {
  describeArmingBlockers,
  deriveSetupArmingReadiness,
  deriveSetupSafetyFlags,
  deriveSetupRebootRequired,
  deriveSetupSensorSummary,
  deriveSetupWarnings,
  SETUP_SENSOR_TOKENS,
  SETUP_SENSOR_TOKENS_MATCH_DECODER,
} from './state';
export type {
  SetupSafetyFlagState,
  SetupSafetyFlags,
  SetupSensorState,
  SetupSensorEntry,
  SetupSensorSummary,
  SetupUnknownSensorBit,
  SetupWarning,
  SetupWarningId,
  SetupWarningInput,
  SetupWarningOwner,
  SetupWarningSeverity,
} from './state';
export { pickTopNotice } from './state';
export type {
  SetupNotice,
  SetupNoticeDomain,
  SetupNoticeSeverity,
  SetupNoticeScope,
} from './state';
export { assembleMotorStaticFacts, bindMotorStaticFacts } from './state';
export {
  deriveMotorDiagnosticsSupport,
  hasEscTelemetrySource,
  visibleMotorTelemetryMetrics,
} from './state';
export type {
  MotorEscTelemetrySource,
  MotorDiagnosticsSupport,
  MotorTelemetryVisibleMetrics,
} from './state';
export type {
  MotorStaticFacts,
  MotorStaticFactsInput,
  MotorStaticFactsBinding,
  MotorStaticFactsSessionIdentity,
  MotorStaticFactsFlightControllerIdentity,
  MotorStaticFactsApiVersionSnapshot,
  MotorStaticFactsFirmwareSnapshot,
  MotorStaticFactsBoardSnapshot,
} from './state';
// Pass 7.6a: exported directly from the module file (not via ./state's
// barrel) because src/core/state/index.ts is outside this pass's
// authorized file allowlist - a deliberate, documented allowlist
// constraint, not a new convention.
export { deriveBatterySemantics } from './state/batteryTelemetry';
export type {
  BatteryFirmwareState,
  BatterySensorValidity,
  BatterySemantics,
} from './state/batteryTelemetry';
export {
  deriveReceiverRssi,
  isGpsPresent,
  deriveGpsCard,
  RSSI_MAX_VALUE,
} from './state/auxTelemetrySemantics';
export {
  ARMING_DISABLE_FLAG_TOKENS,
  ARMING_DISABLE_FLAGS_COUNT,
  SENSOR_PRESENCE_TOKENS,
  BLOCKER_TOKENS_WITH_PROVEN_DESCRIPTION,
  BOXARM_PERMANENT_ID,
  decodeArmingBlockers,
  decodeSensorPresence,
  deriveArmedState,
} from './state/armingBlockers';
export type { BoxIdsOwnerIdentity, BoxIdsResult } from './protocol';
export type {
  ArmingBlockerBit,
  SensorPresenceBit,
  ArmedState,
} from './state/armingBlockers';
export {
  resolveFcToolAvailability,
  resolveAllFcToolAvailability,
  FC_TOOL_IDS,
} from './state/fcTools';
export type {
  FcToolId,
  FcToolBlockReason,
  FcToolAvailability,
  FcToolGateInput,
} from './state/fcTools';
export { deriveSetupDiagnostics } from './state/setupDiagnostics';
export type {
  SetupDiagnosticsInput,
  SetupDiagnosticsView,
  DiagnosticsChannelState,
  DiagnosticsTelemetryStatus,
  DiagnosticsDataState,
  DiagnosticsCompatibility,
  DiagnosticsIdentity,
  DiagnosticsSensors,
  DiagnosticsBlockers,
} from './state/setupDiagnostics';
export type {
  ReceiverRssiSemantics,
  GpsCardSemantics,
} from './state/auxTelemetrySemantics';
export {
  parseFirmwarePresetIndex,
  parseFirmwarePresetDocument,
  expandFirmwarePresetIncludes,
  commandsForPreset,
  filterCompatiblePresets,
  presetFirmwareFamily,
  isSafePresetPath,
  sha256Hex,
} from './state/presetCatalog';
export type {
  FirmwarePresetStatus,
  FirmwarePresetCategory,
  FirmwarePresetSummary,
  FirmwarePresetIndex,
  FirmwarePresetOption,
  FirmwarePresetDocument,
} from './state/presetCatalog';
export {classifyGpsPositionQuality, isGpsPositionTrustworthyForRescue, GPS_PDOP_BANDS} from './state/gpsPositionQuality';
export type {GpsPositionQuality} from './state/gpsPositionQuality';
