export type {
  Transport,
  TransportDataListener,
  TransportDisconnectListener,
  TransportErrorListener,
  TransportUnsubscribe,
} from './transport';

export type {
  MspWireFormat,
  MspProtocolVersion,
  MspDirection,
  MspFrame,
  MspDiagnostic,
  MspDiagnosticCode,
  MspDiagnosticDetailMap,
  MspDiagnosticDetail,
  MspEncodeOptions,
  MspStreamParser,
  MspStreamParserOptions,
  MspIngestEvent,
  MspIngestResult,
  MspTransport,
  MspTransportError,
  MspTransportSessionDetachedEvent,
  MspTransportUnsubscribe,
  MspClientErrorCode,
  MspClientState,
  MspRequestPhase,
  MspRequestOptions,
  MspClientOptions,
  MspClientDiagnosticEvent,
  MspApiVersion,
  MspFcVariantRaw,
  MspBoardInfo,
  MspAttitude,
  MspBatteryState,
  MspAnalog,
  MspRawGpsCompact,
  MspStatusExCompact,
  MspStatusExReadiness,
  MspStatusExDiagnostics,
  MspCompatibilityResult,
  MspFcFamily,
  MspFcVariant,
  FlightControllerIdentity,
  MspRequester,
  MonotonicClock,
  MspPollDefinition,
  TelemetryValue,
  TelemetryPauseReason,
  TelemetryPauseLease,
  MspTelemetryScheduler,
  MspTelemetrySchedulerOptions,
  ExclusiveOperationState,
  OperationExecutionPhase,
  MspOperationContext,
  MspOperationValidationResult,
  MspExclusiveOperation,
  SetupOperationResult,
  MspOperationCoordinator,
  MspOperationSessionSource,
  MspOperationCoordinatorOptions,
} from './protocol';
export {
  MSP_V2_FRAME_ID,
  MSP_MAX_PAYLOAD_BYTES_DEFAULT,
  MSP_PROTOCOL_SIZE_FIELD_CEILING,
  MSP_PARTIAL_FRAME_TIMEOUT_MS_DEFAULT,
  MSP_DIAGNOSTIC_CODES,
  xorChecksumStep,
  xorChecksum,
  crc8DvbS2Step,
  crc8DvbS2,
  encode,
  createMspStreamParser,
  MSP_CLIENT_ERROR_CODES,
  MspClient,
  MspClientError,
  MSP_CLIENT_MAX_PENDING_REQUESTS_DEFAULT,
  MSP_RESPONSE_TIMEOUT_MILLIS,
  MSP_API_VERSION,
  MSP_FC_VARIANT,
  MSP_BOARD_INFO,
  MSP_ATTITUDE,
  MSP_BATTERY_STATE,
  MSP_RAW_GPS,
  MSP_ANALOG,
  MSP_STATUS_EX,
  MSP_BOXIDS,
  STATUS_SENSOR_GPS_BIT,
  BETAFLIGHT_SOURCE_REPO,
  BETAFLIGHT_PINNED_COMMIT,
  BETAFLIGHT_API147_COMMIT,
  INAV_SOURCE_REPO,
  INAV_PINNED_COMMIT,
  EMUFLIGHT_SOURCE_REPO,
  EMUFLIGHT_PINNED_COMMIT,
  MspPayloadReader,
  MspPayloadReadError,
  decodeApiVersion,
  decodeFcVariant,
  decodeBoardInfo,
  decodeAttitude,
  decodeBatteryState,
  decodeAnalog,
  decodeRawGps,
  decodeStatusEx,
  decodeStatusExReadiness,
  decodeStatusExDiagnostics,
  STATUS_EX_FIXED_PREFIX_BYTES,
  checkMspCompatibility,
  MSP_MIN_REQUIRED_API_VERSION_MAJOR,
  MSP_MIN_REQUIRED_API_VERSION_MINOR,
  deriveFcFamily,
  MspIdentificationService,
  MspIncompatibleFirmwareError,
  BoxIdsAcquisition,
  RealClock,
  FakeClock,
  createMspTelemetryScheduler,
  MspOperationOutcomeUnknownError,
  createMspOperationCoordinator,
  MspExclusiveOperationInProgressError,
} from './protocol';
export {deriveOrientationViewState, describeOrientationForAccessibility} from './state';
export type {OrientationViewOffset, OrientationViewState} from './state';
export {deriveArmingReadiness, rankArmingBlockReasons, selectTopArmingBlockReasons} from './state';
export type {ArmingBlockSeverity, ArmingBlockReason, ArmingReadiness, ArmingBlockReasonSelection} from './state';
export {pickTopNotice} from './state';
export type {SetupNotice, SetupNoticeDomain, SetupNoticeSeverity, SetupNoticeScope} from './state';
// Pass 7.6a: exported directly from the module file (not via ./state's
// barrel) because src/core/state/index.ts is outside this pass's
// authorized file allowlist - a deliberate, documented allowlist
// constraint, not a new convention.
export {deriveBatterySemantics} from './state/batteryTelemetry';
export type {BatteryFirmwareState, BatterySensorValidity, BatterySemantics} from './state/batteryTelemetry';
export {deriveReceiverRssi, isGpsPresent, deriveGpsCard, RSSI_MAX_VALUE} from './state/auxTelemetrySemantics';
export {
  ARMING_DISABLE_FLAG_TOKENS,
  ARMING_DISABLE_FLAGS_COUNT,
  SENSOR_PRESENCE_TOKENS,
  BLOCKER_TOKENS_WITH_PROVEN_DESCRIPTION,
  BOXARM_PERMANENT_ID,
  decodeArmingBlockers,
  decodeSensorPresence,
  deriveArmedState,
} from './state/armingBlockers';
export type {ArmingBlockerBit, SensorPresenceBit, ArmedState} from './state/armingBlockers';
export {deriveSetupDiagnostics} from './state/setupDiagnostics';
export type {
  SetupDiagnosticsInput,
  SetupDiagnosticsView,
  DiagnosticsChannelState,
  DiagnosticsTelemetryStatus,
  DiagnosticsDataState,
  DiagnosticsCompatibility,
  DiagnosticsIdentity,
  DiagnosticsSensors,
  DiagnosticsBlockers,
} from './state/setupDiagnostics';
export type {ReceiverRssiSemantics, GpsCardSemantics} from './state/auxTelemetrySemantics';
